import React, { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, ScrollView, Share, StyleSheet, Switch, Text, View } from 'react-native';
import { supabase } from '../../lib/supabase';
import { communitiesProductionService, manageCommunity, type CommunityDetail } from '../../services/communities-production';
import { realtimeChatService, type ChatMember } from '../../services/realtime-chat';
import { CreateCommunitySheet } from './reference-community';
import { Action, Button, ErrorLine, Header, Icon, Page, SearchField, Sheet, Skeleton, ui, usePalette, purple, type ReferencePalette } from '../reconstruction/ui';

const errorText = (error: unknown) => error && typeof error === 'object' && 'message' in error ? String(error.message) : 'Please try again.';

export function CommunityInfo({ id, back, openProfile, openChat, openPosts, onChanged, onDeleted }: { id: string; back: () => void; openProfile: (id: string) => void; openChat: () => void; openPosts: () => void; onChanged: (c: CommunityDetail) => void; onDeleted: () => void }) {
  const c = usePalette();
  const s = useMemo(() => createStyles(c), [c]);
  const [community, setCommunity] = useState<CommunityDetail | null>(null), [members, setMembers] = useState<ChatMember[]>([]), [query, setQuery] = useState('');
  const [view, setView] = useState<'info' | 'settings' | 'requests'>('info'), [edit, setEdit] = useState(false), [confirm, setConfirm] = useState<'leave' | 'delete' | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [requests, setRequests] = useState<{ user_id: number; name: string }[]>([]), [requestsLoading, setRequestsLoading] = useState(false);
  const refresh = async () => {
    const result = await communitiesProductionService.getCommunity(id);
    setCommunity(result);
    onChanged(result);
    if (result.membership === 'created' || result.membership === 'joined') setMembers(await realtimeChatService.loadConversationMembers(Number(id)));
    else setMembers([]);
  };
  useEffect(() => { void refresh().catch(error => setError(errorText(error))); }, [id]);
  const admin = community?.membershipRole === 'admin';
  const joined = community?.membership === 'created' || community?.membership === 'joined';
  const visibleMembers = members.filter(member => `${member.profiles?.full_name || ''} ${member.profiles?.username || ''}`.toLowerCase().includes(query.trim().toLowerCase()));
  const preference = async (key: string, value: boolean) => { setBusy(true); setError(''); try { await manageCommunity(id, 'preferences', { [key]: value }); await refresh(); } catch (error) { setError(errorText(error)); } finally { setBusy(false); } };
  const loadRequests = async () => { setRequestsLoading(true); setError(''); try { const { data, error } = await supabase.from('tbl_community_join_requests').select('user_id,tbl_users(username,fullname)').eq('room_id', Number(id)).eq('status', 'pending').limit(50); if (error) throw error; setRequests((data || []).map((request: any) => ({ user_id: request.user_id, name: request.tbl_users?.fullname || request.tbl_users?.username || `Member ${request.user_id}` }))); } catch (error) { setError(errorText(error)); } finally { setRequestsLoading(false); } };
  const respond = async (user: number, action: 'approve' | 'reject') => { setBusy(true); setError(''); try { await manageCommunity(id, action, { user_id: user }); await loadRequests(); await refresh(); } catch (error) { setError(errorText(error)); } finally { setBusy(false); } };
  const setting = (title: string, subtitle: string, value: boolean, key: string) => <View style={[ui.row, s.settingRow]}><View style={{ flex: 1, gap: 5 }}><Text style={s.settingTitle}>{title}</Text><Text style={s.settingSubtitle}>{subtitle}</Text></View><Switch accessibilityLabel={title} disabled={busy} value={value} onValueChange={next => void preference(key, next)} trackColor={{ true: purple, false: c.iconMuted }} /></View>;

  return <Page>
    <Header title={view === 'info' ? 'Community' : view === 'settings' ? 'Community Settings' : 'Join Requests'} back={view === 'info' ? back : () => setView(view === 'requests' ? 'settings' : 'info')}>
      {view === 'info' ? <><Action name="share-social-outline" label="Share community" onPress={() => { if (community) void Share.share({ message: `Join our community "${community.name}" on WeNitro! Tap here: wenitro://community/join/${id}` }).catch(error => setError(errorText(error))); }} />{admin ? <Action name="settings-outline" label="Community settings" onPress={() => setView('settings')} /> : null}</> : null}
    </Header>
    <ErrorLine text={error} />
    {!community ? <Skeleton /> : <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.content}>
      {view === 'info' ? <>
        <View style={s.identityCard}>
          <View style={s.cover}>{community.coverUrl ? <Image source={{ uri: community.coverUrl }} style={s.coverImage} /> : <View style={s.coverFallback}><Icon name="images-outline" size={34} color={c.iconMuted} /></View>}<View style={s.coverShade} /><View style={s.categoryBadge}><Icon name="people-circle-outline" size={14} color="#FFF" /><Text numberOfLines={1} style={s.categoryText}>{community.category}</Text></View></View>
          <View style={s.identityBody}><View style={s.avatarWrap}>{community.imageUrl ? <Image source={{ uri: community.imageUrl }} style={s.avatar} /> : <View style={[s.avatar, s.avatarFallback]}><Icon name="people" size={34} color={c.accent} /></View>}</View><View style={s.identityCopy}><Text style={s.name}>{community.name}</Text>{community.tagline ? <Text style={s.tagline}>{community.tagline}</Text> : null}<View style={s.metaRow}><Meta icon="people-outline" text={`${community.memberCount ?? members.length} members`} /><Meta icon={community.visibility === 'private' ? 'lock-closed-outline' : 'globe-outline'} text={community.visibility === 'private' ? 'Private' : 'Public'} />{community.membership === 'created' ? <Meta icon="shield-checkmark-outline" text="Created by you" accent /> : null}</View>{community.verifiedOnly || community.requiresApproval || community.adminsOnly ? <View style={s.accessRow}>{community.verifiedOnly ? <Access icon="checkmark-circle-outline" text="Verified only" /> : null}{community.requiresApproval ? <Access icon="person-add-outline" text="Approval required" /> : null}{community.adminsOnly ? <Access icon="megaphone-outline" text="Admin posts" /> : null}</View> : null}</View></View>
        </View>
        <View style={s.card}><Title icon="information-circle-outline" text="About" /><Text selectable style={s.description}>{community.description}</Text>{community.tags.length ? <View style={s.tags}>{community.tags.map(tag => <View key={tag} style={s.tag}><Text style={s.tagText}>#{tag}</Text></View>)}</View> : null}</View>
        {community.rules.length ? <View style={s.card}><Title icon="shield-checkmark-outline" text="Community Rules" />{community.rules.map((rule, index) => <View key={rule.id} style={s.rule}><View style={s.ruleNumber}><Text style={s.ruleNumberText}>{index + 1}</Text></View><Text selectable style={s.ruleText}>{rule.body}</Text></View>)}</View> : null}
        {!joined ? <Button label={community.membership === 'pending' ? 'Join request pending' : community.requiresApproval ? 'Request to join' : 'Join Community'} disabled={community.membership === 'pending'} busy={busy} onPress={() => { setBusy(true); setError(''); void communitiesProductionService.join(id).then(refresh).catch(error => setError(errorText(error))).finally(() => setBusy(false)); }} /> : <View style={s.actionRow}><Pressable accessibilityRole="button" onPress={openPosts} style={[s.primaryAction, { backgroundColor: c.accent }]}><Icon name="newspaper-outline" size={19} color="#FFF" /><Text style={s.primaryActionText}>Community Posts</Text></Pressable><Pressable accessibilityRole="button" onPress={openChat} style={s.secondaryAction}><Icon name="chatbubbles-outline" size={19} color={c.accent} /><Text style={s.secondaryActionText}>Open Chat</Text></Pressable></View>}
        {community.owner ? <Pressable accessibilityRole="button" accessibilityLabel="Open community creator profile" onPress={() => openProfile(community.owner!.id)} style={s.ownerCard}><View style={s.ownerAccent} />{community.owner.avatarUrl ? <Image source={{ uri: community.owner.avatarUrl }} style={s.ownerAvatar} /> : <View style={[s.ownerAvatar, s.avatarFallback]}><Icon name="person" size={23} color={c.iconMuted} /></View>}<View style={{ flex: 1, gap: 4 }}><Text style={s.ownerLabel}>COMMUNITY CREATOR</Text><Text style={s.ownerName}>{community.owner.fullName || community.owner.username}</Text><Text style={s.ownerUsername}>@{community.owner.username}</Text></View><View style={s.ownerAction}><Text style={s.ownerActionText}>View profile</Text><Icon name="chevron-forward" size={16} color={c.accent} /></View></Pressable> : null}
        <View style={s.card}><View style={s.sectionTitleRow}><Icon name="people-outline" size={19} color={c.accent} /><Text style={s.sectionTitle}>Members</Text><Text style={s.sectionCount}>{community.memberCount ?? members.length}</Text></View>{joined ? <>{members.length ? <View style={s.memberPreview}><View style={s.avatarStack}>{members.slice(0, 5).map((member, index) => member.profiles?.avatar_url ? <Image key={member.user_id} source={{ uri: member.profiles.avatar_url }} style={[s.stackAvatar, { marginLeft: index ? -10 : 0 }]} /> : <View key={member.user_id} style={[s.stackAvatar, s.avatarFallback, { marginLeft: index ? -10 : 0 }]}><Icon name="person" size={14} color={c.iconMuted} /></View>)}</View><Text style={s.previewText}>{members.length === 1 ? '1 member in this community' : `${members.length} members in this community`}</Text></View> : null}<SearchField accessibilityLabel="Search members" placeholder="Search members..." value={query} onChangeText={setQuery} style={{ margin: 0 }} />{visibleMembers.length ? visibleMembers.map(member => <Pressable accessibilityRole="button" key={member.user_id} onPress={() => openProfile(String(member.user_id))} style={s.memberRow}>{member.profiles?.avatar_url ? <Image source={{ uri: member.profiles.avatar_url }} style={s.memberAvatar} /> : <View style={[s.memberAvatar, s.avatarFallback]}><Icon name="person-outline" size={21} color={c.iconMuted} /></View>}<View style={{ flex: 1, gap: 3 }}><Text style={s.memberName}>{member.profiles?.full_name || member.profiles?.username || 'Member'}</Text><Text style={s.memberUsername}>@{member.profiles?.username || 'member'}</Text></View>{String(member.user_id) === community.ownerId ? <View style={s.creatorBadge}><Text style={s.creatorText}>Creator</Text></View> : null}<Icon name="chevron-forward" size={17} color={c.iconMuted} /></Pressable>) : <Text style={s.empty}>No members match your search.</Text>}</> : <Text style={s.empty}>Join this community to see its members.</Text>}</View>
        {community.membership === 'joined' ? <Pressable accessibilityRole="button" onPress={() => setConfirm('leave')} style={s.dangerAction}><Text style={s.dangerText}>Leave Community</Text></Pressable> : null}
      </> : view === 'settings' ? <>
        <Text style={s.eyebrow}>INFORMATION</Text><Pressable accessibilityRole="button" onPress={() => setEdit(true)} style={s.settingsCard}><View style={s.settingsIcon}><Icon name="create-outline" color={c.accent} /></View><View style={{ flex: 1, gap: 5 }}><Text style={s.settingTitle}>Edit Community Profile</Text><Text style={s.settingSubtitle}>Update name, description, image and category</Text></View><Icon name="chevron-forward" color={c.iconMuted} size={18} /></Pressable>
        <Text style={s.eyebrow}>MEMBERSHIP & POSTING</Text><View style={s.settingsGroup}>{setting('Verified members only', 'Only verified members can join', community.verifiedOnly, 'verified_only')}{setting('Admin approval required', 'New requests appear in your approval list', community.requiresApproval, 'requires_approval')}{community.requiresApproval ? <Pressable accessibilityRole="button" onPress={() => { setView('requests'); void loadRequests(); }} style={s.requestLink}><Text style={s.requestLinkText}>View Pending Join Requests</Text><Icon name="chevron-forward" size={17} color={c.accent} /></Pressable> : null}{setting('Only admins can post', 'Use the community as an announcements space', community.adminsOnly, 'admins_only')}</View>
        <Pressable accessibilityRole="button" onPress={() => setConfirm('delete')} style={s.dangerAction}><Text style={s.dangerText}>Delete Community</Text></Pressable>
      </> : requestsLoading ? <Skeleton count={2} /> : requests.length ? requests.map(request => <View key={request.user_id} style={s.requestCard}><View style={[s.memberAvatar, s.avatarFallback]}><Icon name="person-outline" size={21} color={c.iconMuted} /></View><Text style={[s.memberName, { flex: 1 }]}>{request.name}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={() => void respond(request.user_id, 'reject')} style={s.rejectButton}><Icon name="close" size={18} color={c.danger} /></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={() => void respond(request.user_id, 'approve')} style={s.approveButton}><Icon name="checkmark" size={18} color="#FFF" /></Pressable></View>) : <View style={s.emptyState}><Icon name="people-outline" size={42} color={c.iconMuted} /><Text style={s.sectionTitle}>No pending requests</Text><Text style={s.empty}>New join requests will appear here.</Text></View>}
    </ScrollView>}
    {edit && community ? <CreateCommunitySheet initial={community} onClose={() => setEdit(false)} onCreated={() => { setEdit(false); void refresh().catch(error => setError(errorText(error))); }} /> : null}
    {confirm ? <Sheet title={confirm === 'leave' ? 'Leave Community?' : 'Delete Community?'} centered close={() => { if (!busy) setConfirm(null); }}><Text style={{ color: c.muted, lineHeight: 21, fontSize: 13 }}>{confirm === 'leave' ? `You will leave ${community?.name || 'this community'} and it will be removed from your community conversations.` : 'This permanently deletes this community, its conversation, polls and posts. This action cannot be undone.'}</Text><Button label="Cancel" disabled={busy} onPress={() => setConfirm(null)} /><Button label={confirm === 'leave' ? 'Leave Community' : 'Delete'} danger busy={busy} onPress={() => { setBusy(true); const task = confirm === 'leave' ? communitiesProductionService.leave(id) : manageCommunity(id, 'delete', { confirmed: true }); void task.then(onDeleted).catch(error => { setError(errorText(error)); setConfirm(null); }).finally(() => setBusy(false)); }} /></Sheet> : null}
  </Page>;

  function Meta({ icon, text, accent = false }: { icon: React.ComponentProps<typeof Icon>['name']; text: string; accent?: boolean }) { return <View style={[s.metaPill, accent && s.ownerPill]}><Icon name={icon} size={14} color={accent ? c.accent : c.muted} /><Text style={[s.metaText, accent && { color: c.accent }]}>{text}</Text></View>; }
  function Access({ icon, text }: { icon: React.ComponentProps<typeof Icon>['name']; text: string }) { return <View style={s.accessPill}><Icon name={icon} size={13} color={c.accent} /><Text style={s.accessText}>{text}</Text></View>; }
  function Title({ icon, text }: { icon: React.ComponentProps<typeof Icon>['name']; text: string }) { return <View style={s.sectionTitleRow}><Icon name={icon} size={19} color={c.accent} /><Text style={s.sectionTitle}>{text}</Text></View>; }
}

const createStyles = (c: ReferencePalette) => StyleSheet.create({
  content: { padding: 16, gap: 14, paddingBottom: 40 }, identityCard: { backgroundColor: c.card, borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: c.border },
  cover: { height: 168, backgroundColor: c.inset }, coverImage: { width: '100%', height: '100%' }, coverFallback: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: c.isDark ? '#17243A' : '#EEF1F8' }, coverShade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 78, backgroundColor: c.isDark ? '#07111FAA' : '#10172A38' }, categoryBadge: { position: 'absolute', left: 12, top: 12, maxWidth: '68%', minHeight: 29, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 15, backgroundColor: '#111827C9', paddingHorizontal: 10 }, categoryText: { color: '#FFF', fontSize: 10, fontWeight: '800' },
  identityBody: { paddingHorizontal: 16, paddingBottom: 17 }, avatarWrap: { width: 88, height: 88, borderRadius: 44, borderWidth: 4, borderColor: c.card, marginTop: -44, backgroundColor: c.card }, avatar: { width: 80, height: 80, borderRadius: 40 }, avatarFallback: { alignItems: 'center', justifyContent: 'center', backgroundColor: c.inset }, identityCopy: { gap: 7, marginTop: 9 }, name: { color: c.text, fontSize: 22, fontWeight: '800' }, tagline: { color: c.muted, fontSize: 12, lineHeight: 18 },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 3 }, metaPill: { minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 9, borderRadius: 14, backgroundColor: c.inset }, ownerPill: { backgroundColor: c.isDark ? '#26214C' : '#F0ECFF' }, metaText: { color: c.muted, fontSize: 10, fontWeight: '600' }, accessRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 2 }, accessPill: { minHeight: 25, flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 12, borderWidth: 1, borderColor: c.isDark ? '#473A89' : '#D9D1FF', backgroundColor: c.isDark ? '#1C1A3A' : '#F5F2FF', paddingHorizontal: 8 }, accessText: { color: c.accent, fontSize: 9, fontWeight: '700' },
  card: { backgroundColor: c.card, borderRadius: 16, borderWidth: 1, borderColor: c.border, padding: 15, gap: 12 }, sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, sectionTitle: { color: c.text, fontSize: 15, fontWeight: '800' }, sectionCount: { color: c.muted, fontSize: 11, marginLeft: 'auto', fontVariant: ['tabular-nums'] }, description: { color: c.muted, fontSize: 12, lineHeight: 19 },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, tag: { backgroundColor: c.isDark ? '#202B45' : '#F0F2F8', borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5 }, tagText: { color: c.accent, fontSize: 10, fontWeight: '700' }, rule: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 }, ruleNumber: { width: 25, height: 25, borderRadius: 13, backgroundColor: c.isDark ? '#302A66' : '#EEEAFE', alignItems: 'center', justifyContent: 'center' }, ruleNumberText: { color: c.accent, fontSize: 10, fontWeight: '800' }, ruleText: { flex: 1, color: c.muted, fontSize: 12, lineHeight: 19, paddingTop: 3 },
  actionRow: { flexDirection: 'row', gap: 10 }, primaryAction: { flex: 1, minHeight: 50, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, primaryActionText: { color: '#FFF', fontSize: 12, fontWeight: '800' }, secondaryAction: { flex: 1, minHeight: 50, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1, borderColor: c.accent, backgroundColor: c.card }, secondaryActionText: { color: c.accent, fontSize: 12, fontWeight: '800' },
  ownerCard: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: c.card, borderRadius: 16, borderWidth: 1, borderColor: c.border, padding: 13, overflow: 'hidden' }, ownerAccent: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4, backgroundColor: c.accent }, ownerAvatar: { width: 50, height: 50, borderRadius: 25 }, ownerLabel: { color: c.accent, fontSize: 8, letterSpacing: .8, fontWeight: '800' }, ownerName: { color: c.text, fontSize: 12, fontWeight: '800' }, ownerUsername: { color: c.muted, fontSize: 9 }, ownerAction: { flexDirection: 'row', alignItems: 'center', gap: 2 }, ownerActionText: { color: c.accent, fontSize: 9, fontWeight: '700' },
  memberPreview: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 2 }, avatarStack: { flexDirection: 'row', alignItems: 'center' }, stackAvatar: { width: 30, height: 30, borderRadius: 15, borderWidth: 2, borderColor: c.card }, previewText: { color: c.muted, fontSize: 9 }, memberRow: { minHeight: 61, flexDirection: 'row', alignItems: 'center', gap: 11, borderTopWidth: 1, borderTopColor: c.border, paddingTop: 10 }, memberAvatar: { width: 42, height: 42, borderRadius: 21 }, memberName: { color: c.text, fontSize: 12, fontWeight: '700' }, memberUsername: { color: c.muted, fontSize: 10 }, creatorBadge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: c.isDark ? '#302A66' : '#EEEAFE' }, creatorText: { color: c.accent, fontSize: 9, fontWeight: '800' }, empty: { color: c.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', paddingVertical: 8 },
  dangerAction: { minHeight: 48, borderWidth: 1, borderColor: c.danger, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, dangerText: { color: c.danger, fontSize: 12, fontWeight: '800' }, eyebrow: { color: c.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1, marginTop: 6 }, settingsCard: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: c.card, borderRadius: 15, borderWidth: 1, borderColor: c.border, padding: 14 }, settingsIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: c.isDark ? '#302A66' : '#EEEAFE', alignItems: 'center', justifyContent: 'center' }, settingsGroup: { backgroundColor: c.card, borderRadius: 15, borderWidth: 1, borderColor: c.border, overflow: 'hidden' }, settingRow: { minHeight: 78, borderBottomWidth: 1, borderColor: c.border }, settingTitle: { color: c.text, fontSize: 12, fontWeight: '700' }, settingSubtitle: { color: c.muted, fontSize: 10, lineHeight: 15 }, requestLink: { minHeight: 48, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: c.border }, requestLinkText: { color: c.accent, fontSize: 11, fontWeight: '700' },
  requestCard: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 13, backgroundColor: c.card, borderRadius: 15, borderWidth: 1, borderColor: c.border }, rejectButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.danger }, approveButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: c.success }, emptyState: { alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 70 },
});
