import { VerifiedBadge } from '../verified-badge';
import React, { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import type { AppData } from '../../../App';
import { communitiesProductionService, type CommunitySummary } from '../../services/communities-production';
import { isSupabaseConfigured, supabase } from '../../lib/supabase';
import { realtimeChatService } from '../../services/realtime-chat';
import { subscribeToAppForeground } from '../../services/app-freshness';
import { Action, Button, ErrorLine, Icon, Page, Sheet, Skeleton, ui, usePalette, purple } from './ui';
const isBackendId = (value: string) => /^[1-9]\d*$/.test(value);
function ChatAvatar({ uri, name }: { uri?: string; name: string }) {
 const c = usePalette(), [failed, setFailed] = useState(false);
 useEffect(() => setFailed(false), [uri]);
 const round = { borderRadius: 24 };
 return uri && !failed ? <Image source={{ uri }} onError={() => setFailed(true)} style={[ui.avatar, round]} /> : <View accessibilityLabel={`${name}'s initials`} style={[ui.avatar, round, { backgroundColor: c.inset, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.border }]}><Text style={{ color: c.accent, fontSize: 15, fontWeight: '700' }}>{name.split(' ').map(word => word[0]).filter(Boolean).slice(0, 2).join('').toUpperCase() || 'WN'}</Text></View>;
}
export function ReferenceMessages({ data, tab, setTab, filter, setFilter, openConversation, startConversation, openCommunity, createCommunity, setData }: { data: AppData; tab: string; setTab: (tab: string) => void; filter: string; setFilter: (filter: string) => void; openProfile: (id: string) => void; openConversation: (id: string) => void; startConversation: (person: { id: number; username: string; fullname: string; profile_image: string }) => Promise<void>; openCommunity: (c: CommunitySummary) => void; createCommunity: () => void; setData: React.Dispatch<React.SetStateAction<AppData>>; openLegacy?: () => void }) {
 const c = usePalette(); const [query, setQuery] = useState(''), [rows, setRows] = useState<CommunitySummary[]>([]), [page, setPage] = useState(1), [more, setMore] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [version, setVersion] = useState(0);
 const [people, setPeople] = useState<{ id: number; username: string; fullname: string; profile_image: string }[]>([]);
 const [inbox, setInbox] = useState<Record<string, any>>({});
 const [creatingGroup, setCreatingGroup] = useState(false);
 const [groupName, setGroupName] = useState('');
 const [groupMembers, setGroupMembers] = useState<string[]>([]);
 const [groupBusy, setGroupBusy] = useState(false);
 useEffect(() => { if (!creatingGroup || data.people.length || people.length) return; void supabase.rpc('list_discoverable_people', { p_limit: 50 }).then(({ data: result }) => { if (Array.isArray(result)) setPeople(result.filter((p: any) => String(p.id) !== data.userId).map((p: any) => ({ id: Number(p.id), username: String(p.username || ''), fullname: String(p.fullname || p.username || ''), profile_image: String(p.profile_image || '') }))); }).catch(() => undefined); }, [creatingGroup]);
 useEffect(() => { setQuery(''); setPage(1); setFilter('All'); }, [tab]);
 useEffect(() => { setPage(1); }, [query, filter]);
 useEffect(() => subscribeToAppForeground(() => setVersion(v => v + 1)), []);
 useEffect(() => { if (tab !== 'Communities') return; let active = true; setLoading(true); const timer = setTimeout(() => { void Promise.all([communitiesProductionService.discover({ query, membership: filter.toLowerCase() as 'all' | 'joined' | 'created', page, pageSize: 25 }), supabase.rpc('list_chat_inbox', { p_message_limit: 1 })]).then(([communities, inbox]) => { if (!active) return; if (inbox.error) throw inbox.error; setRows(current => page === 1 ? communities.items : [...current, ...communities.items]); setMore(communities.hasMore); setInbox(Object.fromEntries((inbox.data || []).map((r: any) => [String(r.id || r.room_id), r]))); setError(''); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); }, query ? 300 : 0); return () => { active = false; clearTimeout(timer); }; }, [tab, query, filter, page, version]);
 useEffect(() => { let active = true; if (tab !== 'Chats' || query.trim().length < 2) { setPeople([]); return; }
 const timer = setTimeout(() => { const safe = query.trim().replace(/[%_,()."\\]/g, ' ').slice(0, 80); void supabase.from('tbl_users').select('id,username,fullname,profile_image').or(`username.ilike.%${safe}%,fullname.ilike.%${safe}%`).limit(20).then(({ data: result, error }) => { if (active) { if (error) setError(error.message); else setPeople((result || []).filter(p => String(p.id) !== data.userId)); } }); }, 350);
 return () => { active = false; clearTimeout(timer); };
 }, [tab, query]);
 const conversations = data.conversations.filter(r => r.roomType !== 'community' && !data.communities.some(cm => cm.id === r.id) && (tab === 'Chats' ? r.type === 'People' : r.type === 'Groups') && r.name.toLowerCase().includes(query.toLowerCase()) && (tab !== 'Groups' || filter !== 'Unread' || r.unread > 0));
 const searchPeople = people.filter(person => !conversations.some(conversation => conversation.userId === String(person.id)));
 const visibleTab = tab === 'Groups' ? 'Activities' : tab;
 const groupPeople = data.people.length ? data.people.map(person => ({ id: person.id, name: person.name, username: person.username, avatar: person.avatar })) : people.map(person => ({ id: String(person.id), name: person.fullname || person.username, username: person.username, avatar: person.profile_image }));
 const createGroup = async () => {
  if (groupName.trim().length < 3 || groupMembers.length < 2) return Alert.alert('Add group details', 'Enter a group name and select at least two people.');
  const memberIds = groupPeople.filter(person => groupMembers.includes(person.id) && isBackendId(person.id)).map(person => Number(person.id));
  if (isSupabaseConfigured && memberIds.length < 2) return Alert.alert('Real members required', 'Select at least two WeNitro members.');
  setGroupBusy(true);
  try {
   const groupId = isSupabaseConfigured ? String(await realtimeChatService.createGroupConversation(groupName.trim(), memberIds)) : `group-${Date.now()}`;
   setData(current => ({ ...current, conversations: current.conversations.some(item => item.id === groupId) ? current.conversations : [{ id: groupId, name: groupName.trim(), type: 'Groups', roomType: 'group', avatar: '', memberCount: groupMembers.length + 1, online: true, unread: 0, memberIds: groupMembers, messages: [] }, ...current.conversations] }));
   setCreatingGroup(false); setGroupName(''); setGroupMembers([]); openConversation(groupId);
  } catch (caught) { Alert.alert('Could not create group', caught instanceof Error ? caught.message : 'Please try again.'); }
  finally { setGroupBusy(false); }
 };
 return <Page><View style={{ height: 52, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Text style={{ color: c.text, fontSize: 21, fontWeight: '700' }}>Messages</Text>{tab !== 'Communities' && <Action name="add-circle-outline" label="Create a group" onPress={() => setCreatingGroup(true)} />}</View><View style={{ height: 42, flexDirection: 'row', borderBottomWidth: 1, borderColor: c.border, paddingHorizontal: 14 }}>{['Chats', 'Activities', 'Communities'].map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: visibleTab === value }} onPress={() => setTab(value === 'Activities' ? 'Groups' : value)} style={{ flex: 1, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 2, borderBottomColor: visibleTab === value ? c.accent : 'transparent' }}><Text style={{ color: visibleTab === value ? c.accent : c.muted, fontSize: 12, fontWeight: '600' }}>{value}</Text></Pressable>)}</View><View style={{ marginHorizontal: 14, marginVertical: 8, height: 42, backgroundColor: c.input, borderWidth: 1, borderColor: c.border, borderRadius: 11, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', gap: 8 }}><Icon name="search-outline" size={18} color={c.muted} /><TextInput accessibilityLabel={tab === 'Chats' ? 'Search chats or users' : tab === 'Groups' ? 'Search activity chats' : 'Search communities'} placeholder={tab === 'Chats' ? 'Search chats or users...' : tab === 'Groups' ? 'Search activity chats...' : 'Search communities...'} placeholderTextColor={c.iconMuted} value={query} onChangeText={setQuery} style={{ flex: 1, color: c.text, fontSize: 12, height: 40, outlineStyle: 'none' } as any} /></View>{tab === 'Communities' && <View style={{ flexDirection: 'row', paddingHorizontal: 14, paddingBottom: 6, gap: 7 }}>{['All', 'Joined', 'Created'].map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: filter === value }} onPress={() => setFilter(value)} style={{ minHeight: 32, paddingHorizontal: 16, borderRadius: 16, backgroundColor: filter === value ? c.accent : c.inset, justifyContent: 'center' }}><Text style={{ color: filter === value ? '#FFF' : c.muted, fontSize: 11, fontWeight: '600' }}>{value}</Text></Pressable>)}</View>}{tab === 'Groups' && <View style={{ flexDirection: 'row', paddingHorizontal: 14, paddingBottom: 6, gap: 7 }}>{['All', 'Unread'].map(value => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: filter === value }} onPress={() => setFilter(value)} style={{ minHeight: 32, paddingHorizontal: 16, borderRadius: 16, backgroundColor: filter === value ? c.accent : c.inset, justifyContent: 'center' }}><Text style={{ color: filter === value ? '#FFF' : c.muted, fontSize: 11, fontWeight: '600' }}>{value}</Text></Pressable>)}</View>}<ErrorLine text={error} />
 {tab === 'Communities' && loading && page === 1 ? <Skeleton count={5} /> : <ScrollView contentContainerStyle={{ paddingHorizontal: 14, paddingBottom: 24 }}>{tab === 'Communities' ? rows.map(room => {
 const conv = data.conversations.find(v => v.id === room.id); const remote = inbox[room.id]; const message = conv?.messages[conv.messages.length - 1]; const latest = remote?.last_message;
 const text = message?.text || latest?.content || latest?.body || ''; const kind = message?.messageType || latest?.message_type; const preview = kind === 'image' ? 'Photo' : kind === 'video' ? 'Video' : kind === 'poll' ? 'Poll' : text;
 const mine = message ? message.mine : String(latest?.sender_id) === data.userId; const at = conv?.lastMessageAt || latest?.created_at || remote?.last_message_at;
 return <Pressable accessibilityRole="button" key={room.id} onPress={() => openCommunity(room)} style={[ui.row, { paddingHorizontal: 0, minHeight: 76, borderBottomWidth: 1, borderColor: c.border }]}>{room.imageUrl ? <Image source={{ uri: room.imageUrl }} style={ui.avatar} /> : <View style={[ui.avatar, { backgroundColor: c.card, alignItems: 'center', justifyContent: 'center' }]}><Icon name="people-outline" color={purple} /></View>}<View style={{ flex: 1, gap: 4 }}><Text numberOfLines={1} style={{ color: c.text, fontSize: 14, fontWeight: '600' }}>{room.name}</Text><Text style={{ color: '#9C90F4', fontSize: 10 }}>{room.category}</Text>{preview ? <Text numberOfLines={1} style={{ color: c.muted, fontSize: 11 }}>{mine ? 'You: ' : ''}{preview}</Text> : null}</View>{at && <Text style={{ color: c.muted, fontSize: 9 }}>{new Date(at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text>}</Pressable>;
 }) : <>{conversations.length ? <Text style={[ui.section, { color: c.muted, marginTop: 6, marginBottom: 4, fontSize: 10 }]}>ACTIVE CONVERSATIONS</Text> : null}{conversations.map(conv => { const last = conv.messages[conv.messages.length - 1]; const at = conv.lastMessageAt || last?.createdAt; return <Pressable accessibilityRole="button" key={conv.id} onPress={() => openConversation(conv.id)} style={[ui.row, { paddingHorizontal: 0, borderBottomWidth: 1, borderColor: c.border, minHeight: 72 }]}><ChatAvatar uri={conv.avatar} name={conv.name} /><View style={{ flex: 1, gap: 6 }}><Text style={{ color: c.text, fontSize: 14, fontWeight: '600' }}>{conv.name} {conv.type === "People" && <VerifiedBadge userId={conv.userId} />}</Text><Text style={{ color: c.muted, fontSize: 11 }} numberOfLines={1}>{last ? `${last.mine ? 'You: ' : ''}${last.text || (last.messageType === 'video' ? 'Video' : 'Photo')}` : 'No messages yet'}</Text></View><View style={{ alignItems: 'flex-end', gap: 7 }}>{at ? <Text style={{ color: c.muted, fontSize: 9 }}>{new Date(at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text> : null}{conv.unread > 0 && <Text style={{ color: 'white', backgroundColor: purple, borderRadius: 11, paddingHorizontal: 6, paddingVertical: 3, fontSize: 9 }}>{conv.unread}</Text>}</View></Pressable>; })}</>}
 {tab === 'Chats' && searchPeople.length ? <Text style={[ui.section, { color: c.muted, marginTop: 16 }]}>PEOPLE</Text> : null}
 {tab === 'Chats' && searchPeople.map(p => <Pressable accessibilityRole="button" key={'person:' + p.id} onPress={() => void startConversation(p)} style={[ui.row, { paddingHorizontal: 0 }]}><ChatAvatar uri={p.profile_image} name={p.fullname || p.username} /><View style={{ flex: 1, gap: 5 }}><Text style={{ color: c.text, fontSize: 13 }}>{p.fullname || p.username} <VerifiedBadge userId={p.id} /></Text><Text style={{ color: c.muted, fontSize: 11 }}>@{p.username}</Text></View><Icon name="chatbubble-outline" color={purple} size={20} /></Pressable>)}
 {!loading && !(tab === 'Communities' ? rows.length : conversations.length + searchPeople.length) && <Text style={{ color: c.muted, fontSize: 13, textAlign: 'center', marginTop: 38 }}>{tab === 'Chats' ? 'No personal chats yet.' : tab === 'Groups' ? 'No activity conversations yet.' : 'No communities found.'}</Text>}{tab === 'Communities' && more && <Button label="Load more" busy={loading} onPress={() => setPage(p => p + 1)} />}</ScrollView>}
 {tab === 'Communities' && <Pressable accessibilityRole="button" accessibilityLabel="Create Community" onPress={createCommunity} style={{ position: 'absolute', bottom: 21, right: 20, width: 50, height: 50, borderRadius: 27, backgroundColor: purple, alignItems: 'center', justifyContent: 'center' }}><Icon name="add" color="#FFF" size={28} /></Pressable>}
 {creatingGroup ? <Sheet title="Create a group" close={() => { if (!groupBusy) setCreatingGroup(false); }}>
  <Text style={{ color: c.muted, fontSize: 12 }}>Choose at least two people</Text>
  <TextInput accessibilityLabel="Group name" value={groupName} onChangeText={setGroupName} placeholder="Group name" placeholderTextColor={c.muted} style={{ minHeight: 48, borderRadius: 12, borderWidth: 1, borderColor: c.border, backgroundColor: c.input, color: c.text, paddingHorizontal: 14 }} />
  <ScrollView style={{ maxHeight: 360 }}>{groupPeople.map(person => { const selected = groupMembers.includes(person.id); return <Pressable key={person.id} accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={() => setGroupMembers(current => selected ? current.filter(id => id !== person.id) : [...current, person.id])} style={[ui.row, { paddingHorizontal: 0, minHeight: 64 }]}><ChatAvatar uri={person.avatar} name={person.name} /><View style={{ flex: 1, gap: 3 }}><Text style={{ color: c.text, fontSize: 14, fontWeight: '700' }}>{person.name} <VerifiedBadge userId={person.id} /></Text><Text style={{ color: c.muted, fontSize: 11 }}>{person.username}</Text></View><View style={{ width: 22, height: 22, borderRadius: 11, borderWidth: 2, borderColor: selected ? purple : c.border, backgroundColor: selected ? purple : 'transparent', alignItems: 'center', justifyContent: 'center' }}>{selected ? <Icon name="checkmark" color="#FFF" size={14} /> : null}</View></Pressable>; })}{!groupPeople.length ? <Text style={{ color: c.muted, fontSize: 12, textAlign: 'center', padding: 18 }}>No people to add yet. Search chats for members first.</Text> : null}</ScrollView>
  <Button label={`Create Group · ${groupMembers.length} selected`} busy={groupBusy} disabled={groupBusy} onPress={() => void createGroup()} />
 </Sheet> : null}
 </Page>;
}
