create table if not exists public.tbl_activity_entry_categories (
  id bigint generated by default as identity primary key,
  event_id integer not null references public.tbl_events(id) on delete cascade,
  name text not null,
  price_paisa bigint not null check (price_paisa > 0),
  capacity integer check (capacity is null or capacity > 0),
  position integer not null default 0 check (position >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, name)
);

create index if not exists tbl_activity_entry_categories_event_idx
  on public.tbl_activity_entry_categories(event_id, active, position, id);

alter table public.tbl_activity_entry_categories enable row level security;
revoke all on public.tbl_activity_entry_categories from anon, authenticated;

alter table public.tbl_activity_payments
  add column if not exists entry_category_id bigint
    references public.tbl_activity_entry_categories(id) on delete restrict,
  add column if not exists entry_category_name text;

alter table public.tbl_event_participants
  add column if not exists entry_category_id bigint
    references public.tbl_activity_entry_categories(id) on delete set null;

create index if not exists tbl_activity_payments_entry_category_idx
  on public.tbl_activity_payments(entry_category_id)
  where entry_category_id is not null;
create index if not exists tbl_event_participants_entry_category_idx
  on public.tbl_event_participants(entry_category_id)
  where entry_category_id is not null;

create or replace function public.list_activity_entry_categories(p_event_id integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare result jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if;
  if not exists (
    select 1 from public.tbl_events e
    where e.id=p_event_id and (
      (e.status='published' and not coalesce(e.is_deleted,false) and not coalesce(e.is_cancelled,false))
      or private.can_manage_activity(e.id,public.get_current_app_user_id())
    )
  ) then raise exception 'Activity is unavailable' using errcode='42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',c.id,'name',c.name,'price_paisa',c.price_paisa,'capacity',c.capacity,
    'position',c.position
  ) order by c.position,c.id),'[]'::jsonb) into result
  from public.tbl_activity_entry_categories c
  where c.event_id=p_event_id and c.active;
  return result;
end;
$$;

create or replace function public.save_activity_entry_categories(
  p_event_id integer,
  p_categories jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  me integer:=public.get_current_app_user_id();
  item jsonb;
  position_number integer:=0;
  result jsonb;
  first_price bigint;
begin
  if not private.can_manage_activity(p_event_id,me) then
    raise exception 'Activity not found or not manageable' using errcode='42501';
  end if;
  if not private.has_active_partner(me) then
    raise exception 'Only approved Partners can configure entry categories' using errcode='42501';
  end if;
  if jsonb_typeof(p_categories) is distinct from 'array'
    or jsonb_array_length(p_categories) not between 1 and 8 then
    raise exception 'Add between 1 and 8 entry categories';
  end if;
  if exists(select 1 from public.tbl_activity_payments where event_id=p_event_id) then
    raise exception 'Entry categories cannot change after checkout has started';
  end if;
  if exists (
    select 1 from (
      select lower(trim(value->>'name')) name,count(*)
      from jsonb_array_elements(p_categories) value
      group by lower(trim(value->>'name')) having count(*)>1
    ) duplicates
  ) then raise exception 'Entry category names must be unique'; end if;

  delete from public.tbl_activity_entry_categories where event_id=p_event_id;
  for item in select value from jsonb_array_elements(p_categories)
  loop
    if length(trim(coalesce(item->>'name',''))) not between 1 and 80
      or coalesce((item->>'price_paisa')::bigint,0) not between 1 and 100000000 then
      raise exception 'Each category needs a name and a valid INR price';
    end if;
    if nullif(item->>'capacity','') is not null and (item->>'capacity')::integer<=0 then
      raise exception 'Category capacity must be positive';
    end if;
    insert into public.tbl_activity_entry_categories(event_id,name,price_paisa,capacity,position)
    values(p_event_id,trim(item->>'name'),(item->>'price_paisa')::bigint,
      nullif(item->>'capacity','')::integer,position_number);
    if position_number=0 then first_price:=(item->>'price_paisa')::bigint; end if;
    position_number:=position_number+1;
  end loop;
  update public.tbl_events set price=first_price/100.0,is_paid=true,updated_by=me,updated_at=now()
  where id=p_event_id;
  result:=public.list_activity_entry_categories(p_event_id);
  return result;
end;
$$;

create or replace function public.prepare_activity_payment(
  p_event_id integer,
  p_entry_category_id bigint
)
returns public.tbl_activity_payments
language plpgsql
security definer
set search_path = ''
as $$
declare
  me integer:=public.get_current_app_user_id();
  event_row public.tbl_events;
  category_row public.tbl_activity_entry_categories;
  participation public.tbl_event_participants;
  payment public.tbl_activity_payments;
  amount_minor bigint;
  occupied integer;
  category_occupied integer;
  generated_order_id text;
begin
  if auth.uid() is null or me is null then raise exception 'Authentication required' using errcode='42501'; end if;
  select * into event_row from public.tbl_events
  where id=p_event_id and status='published' and not coalesce(is_deleted,false)
    and not coalesce(is_cancelled,false) for update;
  if event_row.id is null then raise exception 'Activity is unavailable'; end if;
  if not private.has_active_partner(event_row.created_by) then
    raise exception 'Paid checkout is unavailable while the Partner account is not approved' using errcode='42501';
  end if;
  if event_row.payment_collection_mode<>'cashfree' then raise exception 'Online checkout is unavailable'; end if;
  perform private.assert_registration_complete(p_event_id,me);
  if event_row.created_by=me then raise exception 'Hosts cannot pay to join their own activity'; end if;
  if event_row.registration_close_time is not null and event_row.registration_close_time<now() then
    raise exception 'Registration is closed';
  end if;
  if not event_row.is_paid or event_row.price<=0 then raise exception 'This activity does not require payment'; end if;
  if coalesce(event_row.currency,'INR')<>'INR' then raise exception 'Only INR activities are supported'; end if;

  if exists(select 1 from public.tbl_activity_entry_categories where event_id=p_event_id and active) then
    select * into category_row from public.tbl_activity_entry_categories
    where id=p_entry_category_id and event_id=p_event_id and active for update;
    if category_row.id is null then raise exception 'Choose a valid entry category'; end if;
    amount_minor:=category_row.price_paisa;
  else
    if p_entry_category_id is not null then raise exception 'Invalid entry category'; end if;
    amount_minor:=round(event_row.price*100)::bigint;
    if amount_minor<=0 or abs(event_row.price*100-amount_minor)>0.000001 then
      raise exception 'Activity price must have at most two decimal places';
    end if;
  end if;

  select * into participation from public.tbl_event_participants
  where event_id=p_event_id and user_id=me for update;
  if participation.status in ('approved','going','paid') then raise exception 'You have already joined this activity'; end if;
  if event_row.join_type='approval' and coalesce(participation.status,'')<>'payment_required' then
    raise exception 'Host approval is required before payment';
  end if;
  update public.tbl_activity_payments set status='expired',provider_status=coalesce(provider_status,'LOCAL_EXPIRED'),updated_at=now()
  where event_id=p_event_id and user_id=me and status in ('created','pending') and checkout_expires_at<=now();
  select * into payment from public.tbl_activity_payments
  where event_id=p_event_id and user_id=me and status in ('created','pending') and checkout_expires_at>now()
  order by created_at desc limit 1 for update;
  if payment.id is not null then
    if payment.amount_paisa<>amount_minor or payment.currency<>'INR'
      or payment.entry_category_id is distinct from category_row.id then
      raise exception 'Your category or price changed; withdraw the current attempt before starting another';
    end if;
    return payment;
  end if;
  occupied:=private.activity_occupied_count(p_event_id,me);
  if event_row.max_participants is not null and occupied>=event_row.max_participants then raise exception 'Activity is full'; end if;
  if category_row.capacity is not null then
    select count(*) into category_occupied from public.tbl_activity_payments p
    where p.entry_category_id=category_row.id and (
      p.status='paid' or (p.status in ('created','pending') and p.checkout_expires_at>now())
    );
    if category_occupied>=category_row.capacity then raise exception 'This entry category is full'; end if;
  end if;
  if event_row.join_type<>'approval' then
    insert into public.tbl_event_participants(event_id,user_id,status,responded_at,joined_at,entry_category_id)
    values(p_event_id,me,'payment_required',now(),null,category_row.id)
    on conflict(event_id,user_id) do update set
      status=case when public.tbl_event_participants.status in ('approved','going','paid')
        then public.tbl_event_participants.status else 'payment_required' end,
      responded_at=now(),joined_at=null,entry_category_id=excluded.entry_category_id;
  else
    update public.tbl_event_participants set entry_category_id=category_row.id
    where event_id=p_event_id and user_id=me;
  end if;
  generated_order_id:='wn_'||p_event_id::text||'_'||me::text||'_'||substr(replace(gen_random_uuid()::text,'-',''),1,20);
  insert into public.tbl_activity_payments(
    event_id,user_id,partner_user_id,provider_order_id,amount_paisa,currency,status,
    checkout_expires_at,entry_category_id,entry_category_name
  ) values(
    p_event_id,me,event_row.created_by,generated_order_id,amount_minor,'INR','created',
    now()+interval '20 minutes',category_row.id,category_row.name
  ) returning * into payment;
  return payment;
end;
$$;

create or replace function private.sync_paid_entry_category()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status in ('approved','going','paid') and new.entry_category_id is null then
    select p.entry_category_id into new.entry_category_id
    from public.tbl_activity_payments p
    where p.event_id=new.event_id and p.user_id=new.user_id and p.status='paid'
    order by p.paid_at desc nulls last,p.id desc limit 1;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_paid_entry_category on public.tbl_event_participants;
create trigger sync_paid_entry_category
before insert or update of status on public.tbl_event_participants
for each row execute function private.sync_paid_entry_category();

revoke all on function public.list_activity_entry_categories(integer) from public,anon;
revoke all on function public.save_activity_entry_categories(integer,jsonb) from public,anon;
revoke all on function public.prepare_activity_payment(integer,bigint) from public,anon;
revoke all on function private.sync_paid_entry_category() from public,anon,authenticated;
grant execute on function public.list_activity_entry_categories(integer) to authenticated,service_role;
grant execute on function public.save_activity_entry_categories(integer,jsonb) to authenticated;
grant execute on function public.prepare_activity_payment(integer,bigint) to authenticated,service_role;

comment on table public.tbl_activity_entry_categories is
  'Approved Partner entry categories with server-authoritative Cashfree prices.';
