-- Follow-up hardening for Partner Ecosystem V1.

-- Explicit service-role policies document that these RLS tables are not client-readable.
create policy partner_payout_service_only on public.tbl_partner_payout_accounts
  for all to service_role using(true) with check(true);
create policy partner_finance_config_service_only on public.tbl_partner_finance_config
  for all to service_role using(true) with check(true);
create policy partner_finance_config_history_service_only on public.tbl_partner_finance_config_history
  for all to service_role using(true) with check(true);
create policy partner_financial_events_service_only on public.tbl_partner_financial_events
  for all to service_role using(true) with check(true);
create policy partner_settlements_service_only on public.tbl_partner_settlements
  for all to service_role using(true) with check(true);
create policy partner_finance_audit_service_only on public.tbl_partner_finance_audit
  for all to service_role using(true) with check(true);

create table public.tbl_cashfree_webhook_events (
  id bigint generated by default as identity primary key,
  delivery_key text not null unique,
  event_type text not null,
  provider_order_id text,
  payload_hash text not null,
  status text not null default 'RECEIVED'
    check(status in ('RECEIVED','PROCESSED','FAILED','IGNORED')),
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);
create index cashfree_webhook_events_order_idx
  on public.tbl_cashfree_webhook_events(provider_order_id,received_at desc);
alter table public.tbl_cashfree_webhook_events enable row level security;
revoke all on public.tbl_cashfree_webhook_events from public,anon,authenticated;
grant all on public.tbl_cashfree_webhook_events to service_role;
create policy cashfree_webhook_service_only on public.tbl_cashfree_webhook_events
  for all to service_role using(true) with check(true);
comment on table public.tbl_cashfree_webhook_events is
  'Provider webhook delivery journal. delivery_key is SHA-256(timestamp + exact raw body) for replay-safe processing.';

create or replace function private.protect_paid_payment_evidence()
returns trigger language plpgsql set search_path='' as $$
begin
  if old.status='paid' and (
    new.status is distinct from old.status
    or new.provider_status is distinct from old.provider_status
    or new.provider_payment_id is distinct from old.provider_payment_id
    or new.provider_order_id is distinct from old.provider_order_id
    or new.amount_paisa is distinct from old.amount_paisa
    or new.currency is distinct from old.currency
    or new.paid_at is distinct from old.paid_at
    or new.last_verified_at is distinct from old.last_verified_at
    or new.provider_metadata is distinct from old.provider_metadata
    or new.partner_user_id is distinct from old.partner_user_id
  ) then raise exception 'Verified provider payment evidence is immutable'; end if;
  return new;
end $$;

drop trigger if exists protect_paid_payment_evidence on public.tbl_activity_payments;
create trigger protect_paid_payment_evidence
before update on public.tbl_activity_payments
for each row execute function private.protect_paid_payment_evidence();

create or replace function public.record_activity_payment_provider_state(
  p_order_id text,p_status text,p_provider_status text,
  p_provider_payment_id text default null,p_provider_metadata jsonb default '{}'::jsonb
) returns public.tbl_activity_payments language plpgsql security definer set search_path='' as $$
declare normalized_status text; payment public.tbl_activity_payments;
begin
  normalized_status:=case when p_status in ('created','pending','failed','cancelled','expired') then p_status else 'pending' end;
  select * into payment from public.tbl_activity_payments where provider_order_id=p_order_id for update;
  if payment.id is null then raise exception 'Payment order not found'; end if;
  -- Late or out-of-order non-success events cannot rewrite verified evidence.
  if payment.status='paid' then return payment; end if;
  update public.tbl_activity_payments set status=normalized_status,
    provider_status=nullif(p_provider_status,''),
    provider_payment_id=coalesce(nullif(p_provider_payment_id,''),provider_payment_id),
    provider_metadata=coalesce(provider_metadata,'{}'::jsonb)||coalesce(p_provider_metadata,'{}'::jsonb),
    last_verified_at=now(),updated_at=now()
  where id=payment.id returning * into payment;
  return payment;
end $$;

create or replace function private.get_partner_registrations(p_event_id integer default null)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare me integer:=public.get_current_app_user_id(); result jsonb;
begin
  if auth.uid() is null or not private.has_active_partner(me) then raise exception 'Approved Partner account required' using errcode='42501'; end if;
  if p_event_id is not null and not private.partner_owns_activity(p_event_id) then raise exception 'Activity ownership required' using errcode='42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'participant_id',r.id,'user_id',r.user_id,'event_id',e.id,'activity_title',e.title,
    'display_name',u.fullname,'email',u.email,'phone_e164',u.phone_e164,
    'status',r.status,'payment_status',case when paid.amount>0 then paid.financial_status
      when not e.is_paid then 'FREE' else coalesce(upper(latest.status),'UNPAID') end,
    'amount_paid_paisa',coalesce(paid.amount,0),'registered_at',r.created_at,
    'answers',(select coalesce(jsonb_agg(jsonb_build_object(
      'question_id',q.id,'label',q.label,'value',a.value
    ) order by q.display_order),'[]'::jsonb)
      from public.tbl_activity_registration_answers a
      join public.tbl_activity_registration_questions q on q.id=a.question_id
      where a.event_id=e.id and a.user_id=r.user_id)
  ) order by r.created_at desc),'[]'::jsonb) into result
  from public.tbl_event_participants r
  join public.tbl_events e on e.id=r.event_id
  join public.tbl_users u on u.id=r.user_id
  left join lateral(
    select sum(p.amount_paisa) amount,max(p.financial_status) financial_status
    from public.tbl_activity_payments p
    where p.event_id=e.id and p.user_id=r.user_id and p.status='paid'
  ) paid on true
  left join lateral(
    select p.status from public.tbl_activity_payments p
    where p.event_id=e.id and p.user_id=r.user_id order by p.created_at desc limit 1
  ) latest on true
  where e.created_by=me and (p_event_id is null or e.id=p_event_id) and r.status<>'left';
  return result;
end $$;

create or replace function private.admin_get_partner_finance_config()
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
  if not private.is_finance_admin() then raise exception 'Finance admin access required' using errcode='42501'; end if;
  select to_jsonb(c) into result from public.tbl_partner_finance_config c where c.singleton;
  return result;
end $$;
create or replace function public.admin_get_partner_finance_config()
returns jsonb language sql stable security invoker set search_path='' as $$
  select private.admin_get_partner_finance_config()
$$;

create or replace function private.admin_record_partner_financial_event(
  p_payment_id bigint,p_kind text,p_status text,p_amount_paisa bigint,
  p_provider_reference text,p_idempotency_key text,p_reason text,
  p_metadata jsonb default '{}'::jsonb
) returns jsonb language plpgsql security definer set search_path='' as $$
declare
  me integer:=public.get_current_app_user_id(); payment public.tbl_activity_payments;
  event_row public.tbl_events; result public.tbl_partner_financial_events;
  normalized_kind text:=upper(p_kind); normalized_status text:=upper(p_status);
  successful_refunds bigint;
begin
  if not private.is_finance_admin() or me is null then raise exception 'Finance admin access required' using errcode='42501'; end if;
  if normalized_kind not in ('REFUND','CHARGEBACK','DISPUTE','REVERSAL','ADJUSTMENT')
     or normalized_status not in ('REQUIRED','PENDING','PROCESSING','SUCCEEDED','FAILED','OPEN','RESOLVED') then
    raise exception 'Invalid financial event kind or status' using errcode='22023';
  end if;
  if p_amount_paisa<0 or nullif(btrim(coalesce(p_idempotency_key,'')),'') is null
     or nullif(btrim(coalesce(p_reason,'')),'') is null then
    raise exception 'Amount, idempotency key and reason are required' using errcode='22023';
  end if;
  select * into payment from public.tbl_activity_payments where id=p_payment_id and status='paid' for update;
  if payment.id is null then raise exception 'Verified payment not found'; end if;
  select * into event_row from public.tbl_events where id=payment.event_id;
  if normalized_kind='REFUND' and normalized_status='SUCCEEDED' then
    select coalesce(sum(amount_paisa),0) into successful_refunds
    from public.tbl_partner_financial_events
    where payment_id=payment.id and kind='REFUND' and status='SUCCEEDED';
    if successful_refunds+p_amount_paisa>payment.amount_paisa then raise exception 'Refund total exceeds verified payment'; end if;
  end if;
  insert into public.tbl_partner_financial_events(
    payment_id,event_id,partner_user_id,participant_user_id,kind,status,amount_paisa,
    provider_reference,idempotency_key,reason,metadata,created_by
  ) values(
    payment.id,payment.event_id,event_row.created_by,payment.user_id,normalized_kind,normalized_status,
    p_amount_paisa,nullif(btrim(coalesce(p_provider_reference,'')),''),btrim(p_idempotency_key),
    btrim(p_reason),coalesce(p_metadata,'{}'::jsonb),me
  ) returning * into result;
  update public.tbl_activity_payments set financial_status=case
    when normalized_kind='REFUND' and normalized_status='SUCCEEDED' and successful_refunds+p_amount_paisa>=amount_paisa then 'REFUNDED'
    when normalized_kind in ('CHARGEBACK','REVERSAL') and normalized_status='SUCCEEDED' then 'REVERSED'
    when normalized_kind='DISPUTE' and normalized_status in ('OPEN','PENDING','PROCESSING') then 'DISPUTED'
    when normalized_status in ('REQUIRED','PENDING','PROCESSING','OPEN') then 'ON_HOLD'
    else financial_status end
  where id=payment.id;
  perform private.refresh_partner_settlement(payment.event_id);
  insert into public.tbl_partner_finance_audit(actor_user_id,action,entity_type,entity_id,after_data,reason)
  values(me,'FINANCIAL_EVENT_RECORDED','financial_event',result.id::text,to_jsonb(result),p_reason);
  perform private.enqueue_notification(payment.user_id,'payment_financial_update','Payment update',
    initcap(lower(normalized_kind))||' status: '||normalized_status,payment.event_id::text,me,
    jsonb_build_object('financial_event_id',result.id,'kind',normalized_kind,'status',normalized_status));
  return to_jsonb(result);
end $$;

create or replace function public.admin_record_partner_financial_event(
  p_payment_id bigint,p_kind text,p_status text,p_amount_paisa bigint,
  p_provider_reference text,p_idempotency_key text,p_reason text,
  p_metadata jsonb default '{}'::jsonb
) returns jsonb language sql security invoker set search_path='' as $$
  select private.admin_record_partner_financial_event(
    p_payment_id,p_kind,p_status,p_amount_paisa,p_provider_reference,
    p_idempotency_key,p_reason,p_metadata
  )
$$;

revoke all on function private.protect_paid_payment_evidence(),
  private.get_partner_registrations(integer),private.admin_get_partner_finance_config(),
  private.admin_record_partner_financial_event(bigint,text,text,bigint,text,text,text,jsonb)
from public,anon,authenticated;

revoke all on function public.admin_get_partner_finance_config(),
  public.admin_record_partner_financial_event(bigint,text,text,bigint,text,text,text,jsonb)
from public,anon;
grant execute on function public.admin_get_partner_finance_config(),
  public.admin_record_partner_financial_event(bigint,text,text,bigint,text,text,text,jsonb)
to authenticated;

revoke all on function public.record_activity_payment_provider_state(text,text,text,text,jsonb)
from public,anon,authenticated;
grant execute on function public.record_activity_payment_provider_state(text,text,text,text,jsonb)
to service_role;
