-- WeNitro Partner Ecosystem V1
-- Forward-only production migration. Existing users, activities and payment evidence
-- are preserved. Partner approval and all financial mutations are server-authoritative.

-- ---------------------------------------------------------------------------
-- Partner applications, review history and protected payout destination
-- ---------------------------------------------------------------------------

alter table public.tbl_partner_profiles
  drop constraint if exists tbl_partner_profiles_status_check,
  drop constraint if exists partner_active_name;

update public.tbl_partner_profiles
set status = case lower(status)
  when 'active' then 'APPROVED'
  when 'pending' then 'UNDER_REVIEW'
  when 'suspended' then 'SUSPENDED'
  when 'rejected' then 'REJECTED'
  else 'DRAFT'
end;

alter table public.tbl_partner_profiles
  alter column status set default 'DRAFT',
  add column if not exists activity_types text[] not null default '{}'::text[],
  add column if not exists activity_location text not null default '',
  add column if not exists age_category text not null default '',
  add column if not exists submitted_at timestamptz,
  add column if not exists reviewed_at timestamptz,
  add column if not exists reviewed_by integer references public.tbl_users(id) on delete set null,
  add column if not exists decision_reason text;

alter table public.tbl_partner_profiles
  add constraint tbl_partner_profiles_status_check
    check (status in ('DRAFT','UNDER_REVIEW','APPROVED','REJECTED','SUSPENDED')),
  add constraint partner_approved_name
    check (status <> 'APPROVED' or char_length(btrim(business_name)) >= 2),
  add constraint partner_activity_types_limit
    check (cardinality(activity_types) <= 20),
  add constraint partner_age_category_length
    check (char_length(age_category) <= 80),
  add constraint partner_activity_location_length
    check (char_length(activity_location) <= 240),
  add constraint partner_decision_reason_length
    check (decision_reason is null or char_length(decision_reason) <= 1000);

create table public.tbl_partner_application_history (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.tbl_users(id) on delete restrict,
  from_status text,
  to_status text not null check (to_status in ('DRAFT','UNDER_REVIEW','APPROVED','REJECTED','SUSPENDED')),
  reason text,
  actor_user_id integer references public.tbl_users(id) on delete set null,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index partner_application_history_user_idx
  on public.tbl_partner_application_history(user_id, created_at desc);
alter table public.tbl_partner_application_history enable row level security;
revoke all on public.tbl_partner_application_history from public, anon, authenticated;
grant all on public.tbl_partner_application_history to service_role;

create policy partner_application_history_owner_read
  on public.tbl_partner_application_history for select to authenticated
  using (user_id = public.get_current_app_user_id() or public.is_wenitro_admin());
grant select on public.tbl_partner_application_history to authenticated;

create table public.tbl_partner_payout_accounts (
  user_id integer primary key references public.tbl_users(id) on delete cascade,
  bank_name text not null default '' check (char_length(bank_name) <= 120),
  account_holder_name text not null default '' check (char_length(account_holder_name) <= 160),
  account_number text not null default '' check (char_length(account_number) <= 34),
  ifsc text not null default '' check (char_length(ifsc) <= 20),
  upi_id text not null default '' check (char_length(upi_id) <= 160),
  review_status text not null default 'UNDER_REVIEW'
    check (review_status in ('UNDER_REVIEW','APPROVED','REJECTED','ON_HOLD')),
  reviewed_at timestamptz,
  reviewed_by integer references public.tbl_users(id) on delete set null,
  review_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (account_number <> '' or upi_id <> '')
);

alter table public.tbl_partner_payout_accounts enable row level security;
revoke all on public.tbl_partner_payout_accounts from public, anon, authenticated;
grant all on public.tbl_partner_payout_accounts to service_role;
comment on table public.tbl_partner_payout_accounts is
  'Restricted payout destination. Raw values are never returned by client RPCs; UI receives masked values only. External KMS/tokenisation remains an operations integration.';

create or replace function private.normalize_partner_status()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  new.status := case upper(coalesce(new.status, 'DRAFT'))
    when 'ACTIVE' then 'APPROVED'
    when 'PENDING' then 'UNDER_REVIEW'
    when 'DRAFT' then 'DRAFT'
    when 'UNDER_REVIEW' then 'UNDER_REVIEW'
    when 'APPROVED' then 'APPROVED'
    when 'REJECTED' then 'REJECTED'
    when 'SUSPENDED' then 'SUSPENDED'
    else new.status
  end;
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists normalize_partner_status on public.tbl_partner_profiles;
create trigger normalize_partner_status
before insert or update of status on public.tbl_partner_profiles
for each row execute function private.normalize_partner_status();

create or replace function private.has_active_partner(p_user_id integer)
returns boolean language sql stable security definer set search_path = '' as $$
  select private.partner_eligible(p_user_id)
    and exists (
      select 1 from public.tbl_partner_profiles p
      where p.user_id = p_user_id and p.status = 'APPROVED'
    )
$$;

create or replace function private.sync_partner_capability()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  update public.tbl_users
  set account_type = case
    when tg_op <> 'DELETE' and new.status = 'APPROVED' then 'partner'
    else 'individual'
  end
  where id = coalesce(new.user_id, old.user_id);
  return null;
end $$;

update public.tbl_users u
set account_type = case when exists (
  select 1 from public.tbl_partner_profiles p
  where p.user_id = u.id and p.status = 'APPROVED'
) then 'partner' else 'individual' end
where u.account_type = 'partner';

create or replace function private.is_finance_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce(auth.jwt()->'app_metadata'->>'role', '') in ('super_admin','finance_admin')
$$;

create or replace function private.mask_financial_value(p_value text, p_visible integer default 4)
returns text language sql immutable set search_path = '' as $$
  select case
    when nullif(btrim(coalesce(p_value, '')), '') is null then ''
    when char_length(p_value) <= p_visible then repeat('•', char_length(p_value))
    else repeat('•', greatest(4, char_length(p_value) - p_visible)) || right(p_value, p_visible)
  end
$$;

create or replace function private.get_my_partner_profile()
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
  me integer := public.get_current_app_user_id();
  profile jsonb;
  payout jsonb;
begin
  if auth.uid() is null or me is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  select to_jsonb(p) into profile
  from public.tbl_partner_profiles p where p.user_id = me;
  select jsonb_build_object(
    'bank_name', a.bank_name,
    'account_holder_name', a.account_holder_name,
    'account_number_masked', private.mask_financial_value(a.account_number, 4),
    'ifsc_masked', private.mask_financial_value(a.ifsc, 4),
    'upi_id_masked', case when a.upi_id = '' then ''
      when position('@' in a.upi_id) > 0 then left(a.upi_id,1) || '•••@' || split_part(a.upi_id,'@',2)
      else private.mask_financial_value(a.upi_id,3) end,
    'review_status', a.review_status,
    'review_reason', a.review_reason,
    'updated_at', a.updated_at
  ) into payout
  from public.tbl_partner_payout_accounts a where a.user_id = me;
  return jsonb_build_object(
    'profile', profile,
    'payout_account', payout,
    'eligible', private.partner_eligible(me),
    'can_host_paid', private.has_active_partner(me)
  );
end $$;

create or replace function private.submit_partner_application(p_application jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  me integer := public.get_current_app_user_id();
  previous_status text;
  next_status text;
  activity_types text[];
  profile public.tbl_partner_profiles;
begin
  if auth.uid() is null or not private.partner_eligible(me) then
    raise exception 'Verify your email or phone before applying as a Partner' using errcode = '42501';
  end if;
  if jsonb_typeof(p_application) is distinct from 'object' then
    raise exception 'Partner application must be an object' using errcode = '22023';
  end if;
  if char_length(btrim(coalesce(p_application->>'business_name',''))) not between 2 and 120
     or char_length(btrim(coalesce(p_application->>'city',''))) not between 2 and 120
     or char_length(btrim(coalesce(p_application->>'activity_location',''))) not between 2 and 240
     or char_length(btrim(coalesce(p_application->>'age_category',''))) not between 2 and 80 then
    raise exception 'Business name, city, activity location and age category are required' using errcode = '22023';
  end if;
  if jsonb_typeof(coalesce(p_application->'activity_types','[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_application->'activity_types','[]'::jsonb)) not between 1 and 20 then
    raise exception 'Choose at least one activity type' using errcode = '22023';
  end if;
  select array_agg(distinct btrim(value) order by btrim(value)) into activity_types
  from jsonb_array_elements_text(p_application->'activity_types') x(value)
  where btrim(value) <> '';
  if coalesce(cardinality(activity_types), 0) = 0 then
    raise exception 'Choose at least one activity type' using errcode = '22023';
  end if;

  perform 1 from public.tbl_users where id = me for update;
  select status into previous_status from public.tbl_partner_profiles where user_id = me for update;
  if previous_status = 'SUSPENDED' then
    raise exception 'A suspended Partner account must be reviewed by WeNitro' using errcode = '42501';
  end if;
  next_status := case when previous_status='APPROVED' then 'APPROVED' else 'UNDER_REVIEW' end;

  insert into public.tbl_partner_profiles(
    user_id, business_name, description, city, activity_types,
    activity_location, age_category, status, submitted_at,
    reviewed_at, reviewed_by, decision_reason
  ) values (
    me, btrim(p_application->>'business_name'),
    left(btrim(coalesce(p_application->>'description','')), 1000),
    btrim(p_application->>'city'), activity_types,
    btrim(p_application->>'activity_location'), btrim(p_application->>'age_category'),
    next_status, now(), null, null, null
  )
  on conflict(user_id) do update set
    business_name = excluded.business_name,
    description = excluded.description,
    city = excluded.city,
    activity_types = excluded.activity_types,
    activity_location = excluded.activity_location,
    age_category = excluded.age_category,
    status = next_status, submitted_at = now(),
    reviewed_at = case when next_status='APPROVED' then public.tbl_partner_profiles.reviewed_at else null end,
    reviewed_by = case when next_status='APPROVED' then public.tbl_partner_profiles.reviewed_by else null end,
    decision_reason = case when next_status='APPROVED' then public.tbl_partner_profiles.decision_reason else null end,
    updated_at = now()
  returning * into profile;

  if nullif(btrim(coalesce(p_application->>'account_number','')), '') is null
     and nullif(btrim(coalesce(p_application->>'upi_id','')), '') is null then
    raise exception 'Provide a bank account number or UPI ID' using errcode = '22023';
  end if;

  insert into public.tbl_partner_payout_accounts(
    user_id, bank_name, account_holder_name, account_number, ifsc, upi_id,
    review_status, reviewed_at, reviewed_by, review_reason, updated_at
  ) values (
    me,
    left(btrim(coalesce(p_application->>'bank_name','')),120),
    left(btrim(coalesce(p_application->>'account_holder_name','')),160),
    left(regexp_replace(coalesce(p_application->>'account_number',''),'[^A-Za-z0-9]','','g'),34),
    upper(left(regexp_replace(coalesce(p_application->>'ifsc',''),'\s','','g'),20)),
    lower(left(btrim(coalesce(p_application->>'upi_id','')),160)),
    'UNDER_REVIEW', null, null, null, now()
  )
  on conflict(user_id) do update set
    bank_name = excluded.bank_name,
    account_holder_name = excluded.account_holder_name,
    account_number = excluded.account_number,
    ifsc = excluded.ifsc,
    upi_id = excluded.upi_id,
    review_status = 'UNDER_REVIEW', reviewed_at = null,
    reviewed_by = null, review_reason = null, updated_at = now();

  insert into public.tbl_partner_application_history(
    user_id, from_status, to_status, actor_user_id, snapshot
  ) values (me, previous_status, next_status, me, to_jsonb(profile));

  perform private.enqueue_notification(
    me, 'partner_application_submitted', 'Partner application submitted',
    case when next_status='APPROVED'
      then 'Your Partner profile was updated. Payout details are under review; paid hosting remains available.'
      else 'Your application is under review. We will notify you when a decision is made.' end,
    me::text, null, jsonb_build_object('status',next_status,'payout_status','UNDER_REVIEW')
  );
  return private.get_my_partner_profile();
end $$;

create or replace function public.submit_partner_application(p_application jsonb)
returns jsonb language sql security invoker set search_path = '' as $$
  select private.submit_partner_application(p_application)
$$;

-- Compatibility endpoint: old clients now submit for review and can never self-approve.
create or replace function private.save_my_partner_profile(
  p_business_name text, p_description text default '', p_city text default ''
) returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  raise exception 'Complete the updated Partner application, including payout details, to submit for review'
    using errcode='22023';
end
$$;

create or replace function public.save_my_partner_profile(
  p_business_name text, p_description text default '', p_city text default ''
) returns jsonb language sql security invoker set search_path = '' as $$
  select private.save_my_partner_profile(p_business_name,p_description,p_city)
$$;

create or replace function private.admin_list_partner_applications(p_status text default null)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare result jsonb;
begin
  if not public.is_wenitro_admin() then raise exception 'Admin access required' using errcode='42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'user_id',p.user_id,'business_name',p.business_name,'description',p.description,
    'city',p.city,'activity_types',p.activity_types,'activity_location',p.activity_location,
    'age_category',p.age_category,'status',p.status,'submitted_at',p.submitted_at,
    'reviewed_at',p.reviewed_at,'decision_reason',p.decision_reason,
    'user',jsonb_build_object('fullname',u.fullname,'username',u.username,'email',u.email,'phone_e164',u.phone_e164),
    'payout_account',case when a.user_id is null then null else jsonb_build_object(
      'bank_name',a.bank_name,'account_holder_name',a.account_holder_name,
      'account_number_masked',private.mask_financial_value(a.account_number,4),
      'ifsc_masked',private.mask_financial_value(a.ifsc,4),
      'upi_id_masked',private.mask_financial_value(a.upi_id,4),
      'review_status',a.review_status,'review_reason',a.review_reason
    ) end
  ) order by p.submitted_at desc nulls last),'[]'::jsonb) into result
  from public.tbl_partner_profiles p
  join public.tbl_users u on u.id=p.user_id
  left join public.tbl_partner_payout_accounts a on a.user_id=p.user_id
  where p_status is null or p.status=upper(p_status);
  return result;
end $$;

create or replace function public.admin_list_partner_applications(p_status text default null)
returns jsonb language sql stable security invoker set search_path = '' as $$
  select private.admin_list_partner_applications(p_status)
$$;

create or replace function private.admin_review_partner_application(
  p_user_id integer, p_status text, p_reason text default null
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  me integer := public.get_current_app_user_id();
  target_status text := upper(coalesce(p_status,''));
  previous_status text;
  profile public.tbl_partner_profiles;
begin
  if not public.is_wenitro_admin() or me is null then raise exception 'Admin access required' using errcode='42501'; end if;
  if target_status not in ('APPROVED','REJECTED','SUSPENDED','UNDER_REVIEW') then
    raise exception 'Invalid Partner decision' using errcode='22023';
  end if;
  if target_status in ('REJECTED','SUSPENDED') and nullif(btrim(coalesce(p_reason,'')),'') is null then
    raise exception 'A reason is required' using errcode='22023';
  end if;
  select status into previous_status from public.tbl_partner_profiles where user_id=p_user_id for update;
  if previous_status is null then raise exception 'Partner application not found'; end if;
  update public.tbl_partner_profiles set
    status=target_status, reviewed_at=now(), reviewed_by=me,
    decision_reason=nullif(btrim(coalesce(p_reason,'')),''), updated_at=now()
  where user_id=p_user_id returning * into profile;
  update public.tbl_partner_payout_accounts set
    review_status=case when target_status='APPROVED' then 'APPROVED'
      when target_status='SUSPENDED' then 'ON_HOLD'
      when target_status='REJECTED' then 'REJECTED' else 'UNDER_REVIEW' end,
    reviewed_at=now(), reviewed_by=me,
    review_reason=nullif(btrim(coalesce(p_reason,'')),''), updated_at=now()
  where user_id=p_user_id;
  insert into public.tbl_partner_application_history(user_id,from_status,to_status,reason,actor_user_id,snapshot)
  values(p_user_id,previous_status,target_status,nullif(btrim(coalesce(p_reason,'')),''),me,to_jsonb(profile));
  perform private.enqueue_notification(
    p_user_id,'partner_application_decision',
    case target_status when 'APPROVED' then 'Partner account approved'
      when 'REJECTED' then 'Partner application needs attention'
      when 'SUSPENDED' then 'Partner account suspended' else 'Partner application under review' end,
    coalesce(nullif(btrim(coalesce(p_reason,'')),''),case when target_status='APPROVED'
      then 'You can now host paid activities.' else 'Open your Partner profile for details.' end),
    p_user_id::text,me,jsonb_build_object('status',target_status)
  );
  return to_jsonb(profile);
end $$;

create or replace function public.admin_review_partner_application(
  p_user_id integer, p_status text, p_reason text default null
) returns jsonb language sql security invoker set search_path = '' as $$
  select private.admin_review_partner_application(p_user_id,p_status,p_reason)
$$;

-- ---------------------------------------------------------------------------
-- Server-enforced paid hosting and configurable fee/tax policy
-- ---------------------------------------------------------------------------

alter table public.tbl_events
  add column if not exists payment_collection_mode text not null default 'cashfree';
alter table public.tbl_events
  drop constraint if exists tbl_events_payment_collection_mode_check;
alter table public.tbl_events
  add constraint tbl_events_payment_collection_mode_check
    check (payment_collection_mode in ('cashfree','onsite'));
comment on column public.tbl_events.price is
  'Server-authoritative participation price in INR. Paid Partner activities use the configured collection mode.';

create or replace function private.enforce_partner_paid_hosting()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if coalesce(new.is_paid,false) or coalesce(new.price,0)>0 then
    if not private.has_active_partner(new.created_by) then
      raise exception 'Only an approved Partner can host paid activities' using errcode='42501';
    end if;
    if coalesce(new.price,0)<=0 then raise exception 'Paid activities require a positive price'; end if;
    new.is_paid := true;
    new.payment_collection_mode := coalesce(nullif(new.payment_collection_mode,''),'cashfree');
  else
    new.is_paid := false;
    new.price := 0;
  end if;
  return new;
end $$;

drop trigger if exists enforce_partner_paid_hosting on public.tbl_events;
create trigger enforce_partner_paid_hosting
before insert or update of is_paid, price, created_by, payment_collection_mode
on public.tbl_events for each row execute function private.enforce_partner_paid_hosting();

create table public.tbl_partner_finance_config (
  singleton boolean primary key default true check(singleton),
  platform_fee_bps integer not null default 1000 check(platform_fee_bps between 0 and 10000),
  gst_enabled boolean not null default false,
  gst_bps integer not null default 0 check(gst_bps between 0 and 10000),
  gst_basis text not null default 'disabled' check(gst_basis in ('disabled','gross','platform_fee')),
  settlement_days integer not null default 7 check(settlement_days between 0 and 90),
  updated_at timestamptz not null default now(),
  updated_by integer references public.tbl_users(id) on delete set null,
  check ((not gst_enabled and gst_bps=0 and gst_basis='disabled') or (gst_enabled and gst_bps>0 and gst_basis<>'disabled'))
);
insert into public.tbl_partner_finance_config(singleton) values(true) on conflict(singleton) do nothing;
alter table public.tbl_partner_finance_config enable row level security;
revoke all on public.tbl_partner_finance_config from public,anon,authenticated;
grant all on public.tbl_partner_finance_config to service_role;
comment on table public.tbl_partner_finance_config is
  'Auditable server fee policy. GST is disabled until finance explicitly supplies an approved rate and basis.';

create table public.tbl_partner_finance_config_history (
  id bigint generated by default as identity primary key,
  platform_fee_bps integer not null,
  gst_enabled boolean not null,
  gst_bps integer not null,
  gst_basis text not null,
  settlement_days integer not null,
  changed_by integer references public.tbl_users(id) on delete set null,
  reason text not null,
  created_at timestamptz not null default now()
);
alter table public.tbl_partner_finance_config_history enable row level security;
revoke all on public.tbl_partner_finance_config_history from public,anon,authenticated;
grant all on public.tbl_partner_finance_config_history to service_role;

create or replace function private.platform_fee_bps()
returns integer language sql stable security definer set search_path = '' as $$
  select platform_fee_bps from public.tbl_partner_finance_config where singleton
$$;

alter table public.tbl_activity_payments
  drop constraint if exists payment_fee_snapshot_valid,
  add column if not exists gst_bps integer,
  add column if not exists gst_paisa bigint,
  add column if not exists gst_basis text,
  add column if not exists financial_status text not null default 'OPEN',
  add column if not exists partner_user_id integer references public.tbl_users(id) on delete restrict;

alter table public.tbl_activity_payments
  add constraint payment_fee_snapshot_valid check (
    (platform_fee_bps is null and platform_fee_paisa is null and partner_net_paisa is null and gst_paisa is null)
    or
    (platform_fee_bps between 0 and 10000 and platform_fee_paisa>=0 and
     coalesce(gst_bps,0) between 0 and 10000 and coalesce(gst_paisa,0)>=0 and
     partner_net_paisa>=0 and platform_fee_paisa+coalesce(gst_paisa,0)+partner_net_paisa=amount_paisa)
  ),
  add constraint payment_financial_status_check
    check(financial_status in ('OPEN','PAYABLE','SETTLED','REFUND_REQUIRED','REFUNDED','DISPUTED','REVERSED','ON_HOLD'));

create unique index activity_payments_provider_payment_unique
  on public.tbl_activity_payments(provider_payment_id)
  where provider_payment_id is not null;

create or replace function private.snapshot_activity_payment_fee()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  config public.tbl_partner_finance_config;
  tax_base bigint;
begin
  if tg_op='UPDATE' and old.status='paid' then
    if new.amount_paisa is distinct from old.amount_paisa
       or new.currency is distinct from old.currency
       or new.provider_order_id is distinct from old.provider_order_id
       or new.provider_payment_id is distinct from old.provider_payment_id
       or new.platform_fee_bps is distinct from old.platform_fee_bps
       or new.platform_fee_paisa is distinct from old.platform_fee_paisa
       or new.gst_bps is distinct from old.gst_bps
       or new.gst_paisa is distinct from old.gst_paisa
       or new.gst_basis is distinct from old.gst_basis
       or new.partner_net_paisa is distinct from old.partner_net_paisa
       or new.paid_at is distinct from old.paid_at then
      raise exception 'Verified payment evidence and accounting are immutable';
    end if;
  end if;
  if new.status='paid' and (tg_op='INSERT' or old.status is distinct from 'paid') then
    select * into config from public.tbl_partner_finance_config where singleton;
    new.platform_fee_bps := config.platform_fee_bps;
    new.platform_fee_paisa := round(new.amount_paisa::numeric*config.platform_fee_bps/10000)::bigint;
    new.gst_bps := case when config.gst_enabled then config.gst_bps else 0 end;
    new.gst_basis := config.gst_basis;
    tax_base := case config.gst_basis when 'gross' then new.amount_paisa
      when 'platform_fee' then new.platform_fee_paisa else 0 end;
    new.gst_paisa := case when config.gst_enabled
      then round(tax_base::numeric*config.gst_bps/10000)::bigint else 0 end;
    if new.platform_fee_paisa+new.gst_paisa>new.amount_paisa then
      raise exception 'Configured deductions exceed gross payment';
    end if;
    new.partner_net_paisa := new.amount_paisa-new.platform_fee_paisa-new.gst_paisa;
    new.financial_status := 'PAYABLE';
  elsif new.status<>'paid' and tg_op='INSERT' then
    new.platform_fee_bps:=null; new.platform_fee_paisa:=null;
    new.gst_bps:=null; new.gst_paisa:=null; new.gst_basis:=null;
    new.partner_net_paisa:=null;
  end if;
  return new;
end $$;

drop trigger if exists snapshot_activity_payment_fee on public.tbl_activity_payments;
create trigger snapshot_activity_payment_fee
before insert or update on public.tbl_activity_payments
for each row execute function private.snapshot_activity_payment_fee();

-- ---------------------------------------------------------------------------
-- Append-only financial events, refunds and settlement control
-- ---------------------------------------------------------------------------

create table public.tbl_partner_financial_events (
  id bigint generated by default as identity primary key,
  payment_id bigint references public.tbl_activity_payments(id) on delete restrict,
  event_id integer not null references public.tbl_events(id) on delete restrict,
  partner_user_id integer not null references public.tbl_users(id) on delete restrict,
  participant_user_id integer references public.tbl_users(id) on delete restrict,
  kind text not null check(kind in ('PAYMENT','REFUND','CHARGEBACK','DISPUTE','REVERSAL','ADJUSTMENT')),
  status text not null check(status in ('REQUIRED','PENDING','PROCESSING','SUCCEEDED','FAILED','OPEN','RESOLVED')),
  amount_paisa bigint not null check(amount_paisa>=0),
  currency text not null default 'INR' check(currency='INR'),
  provider_reference text,
  idempotency_key text not null unique,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_by integer references public.tbl_users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index partner_financial_events_partner_idx
  on public.tbl_partner_financial_events(partner_user_id, created_at desc);
create index partner_financial_events_payment_idx
  on public.tbl_partner_financial_events(payment_id, created_at desc);
alter table public.tbl_partner_financial_events enable row level security;
revoke all on public.tbl_partner_financial_events from public,anon,authenticated;
grant all on public.tbl_partner_financial_events to service_role;

create table public.tbl_partner_settlements (
  id bigint generated by default as identity primary key,
  event_id integer not null unique references public.tbl_events(id) on delete restrict,
  partner_user_id integer not null references public.tbl_users(id) on delete restrict,
  status text not null default 'PENDING'
    check(status in ('PENDING','PROCESSING','PAID','FAILED','ON_HOLD')),
  gross_paisa bigint not null default 0 check(gross_paisa>=0),
  platform_fee_paisa bigint not null default 0 check(platform_fee_paisa>=0),
  gst_paisa bigint not null default 0 check(gst_paisa>=0),
  refund_paisa bigint not null default 0 check(refund_paisa>=0),
  expected_net_paisa bigint not null default 0 check(expected_net_paisa>=0),
  eligible_at timestamptz,
  due_at timestamptz,
  paid_at timestamptz,
  payout_reference text,
  note text,
  updated_by integer references public.tbl_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index partner_settlements_partner_idx
  on public.tbl_partner_settlements(partner_user_id,status,due_at);
alter table public.tbl_partner_settlements enable row level security;
revoke all on public.tbl_partner_settlements from public,anon,authenticated;
grant all on public.tbl_partner_settlements to service_role;
comment on table public.tbl_partner_settlements is
  'Manual-control settlement ledger. PAID requires a recorded payout reference; this table never claims to execute a bank payout.';

create table public.tbl_partner_finance_audit (
  id bigint generated by default as identity primary key,
  actor_user_id integer references public.tbl_users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  before_data jsonb,
  after_data jsonb,
  reason text,
  created_at timestamptz not null default now()
);
alter table public.tbl_partner_finance_audit enable row level security;
revoke all on public.tbl_partner_finance_audit from public,anon,authenticated;
grant all on public.tbl_partner_finance_audit to service_role;

create or replace function private.block_immutable_partner_records()
returns trigger language plpgsql set search_path='' as $$
begin
  raise exception 'Audit and financial history are immutable';
end $$;

create trigger partner_history_immutable before update or delete on public.tbl_partner_application_history
for each row execute function private.block_immutable_partner_records();
create trigger partner_financial_events_immutable before update or delete on public.tbl_partner_financial_events
for each row execute function private.block_immutable_partner_records();
create trigger partner_finance_audit_immutable before update or delete on public.tbl_partner_finance_audit
for each row execute function private.block_immutable_partner_records();
create trigger partner_finance_config_history_immutable before update or delete on public.tbl_partner_finance_config_history
for each row execute function private.block_immutable_partner_records();

create or replace function private.refresh_partner_settlement(p_event_id integer)
returns void language plpgsql security definer set search_path='' as $$
declare
  e public.tbl_events;
  config public.tbl_partner_finance_config;
  gross bigint; fee bigint; gst bigint; refunded bigint; net bigint;
begin
  select * into e from public.tbl_events where id=p_event_id;
  if e.id is null then return; end if;
  select * into config from public.tbl_partner_finance_config where singleton;
  select coalesce(sum(amount_paisa),0),coalesce(sum(platform_fee_paisa),0),
    coalesce(sum(gst_paisa),0)
  into gross,fee,gst from public.tbl_activity_payments
  where event_id=p_event_id and status='paid';
  select coalesce(sum(amount_paisa),0) into refunded
  from public.tbl_partner_financial_events
  where event_id=p_event_id and kind in ('REFUND','CHARGEBACK','REVERSAL') and status='SUCCEEDED';
  net:=greatest(0,gross-fee-gst-refunded);
  insert into public.tbl_partner_settlements(
    event_id,partner_user_id,status,gross_paisa,platform_fee_paisa,gst_paisa,
    refund_paisa,expected_net_paisa,eligible_at,due_at
  ) values (
    p_event_id,e.created_by,'PENDING',gross,fee,gst,refunded,net,
    e.event_end_time,e.event_end_time+make_interval(days=>config.settlement_days)
  ) on conflict(event_id) do update set
    gross_paisa=excluded.gross_paisa,platform_fee_paisa=excluded.platform_fee_paisa,
    gst_paisa=excluded.gst_paisa,refund_paisa=excluded.refund_paisa,
    expected_net_paisa=excluded.expected_net_paisa,
    eligible_at=excluded.eligible_at,due_at=excluded.due_at,
    status=case when public.tbl_partner_settlements.status='PAID'
      and public.tbl_partner_settlements.expected_net_paisa<>excluded.expected_net_paisa then 'ON_HOLD'
      else public.tbl_partner_settlements.status end,
    updated_at=now();
end $$;

create or replace function private.queue_required_refund(
  p_payment public.tbl_activity_payments, p_reason text
) returns void language plpgsql security definer set search_path='' as $$
declare host_id integer;
begin
  select created_by into host_id from public.tbl_events where id=p_payment.event_id;
  insert into public.tbl_partner_financial_events(
    payment_id,event_id,partner_user_id,participant_user_id,kind,status,
    amount_paisa,idempotency_key,reason
  ) values (
    p_payment.id,p_payment.event_id,host_id,p_payment.user_id,'REFUND','REQUIRED',
    p_payment.amount_paisa,'refund-required:'||p_payment.id::text,p_reason
  ) on conflict(idempotency_key) do nothing;
  update public.tbl_activity_payments set financial_status='REFUND_REQUIRED'
  where id=p_payment.id and financial_status<>'REFUNDED';
  perform private.enqueue_notification(
    p_payment.user_id,'payment_refund_required','Refund review started',
    'Your payment was verified but the activity could not confirm your place. WeNitro has opened a refund case.',
    p_payment.event_id::text,null,jsonb_build_object('payment_id',p_payment.id,'reason',p_reason)
  );
  perform private.refresh_partner_settlement(p_payment.event_id);
end $$;

-- ---------------------------------------------------------------------------
-- Payment lifecycle: provider truth first, seat second, explicit refund path
-- ---------------------------------------------------------------------------

create or replace function public.prepare_activity_payment(p_event_id integer)
returns public.tbl_activity_payments language plpgsql security definer set search_path='' as $$
declare
  me integer:=public.get_current_app_user_id();
  event_row public.tbl_events;
  participation public.tbl_event_participants;
  payment public.tbl_activity_payments;
  amount_minor bigint; occupied integer; generated_order_id text;
begin
  if auth.uid() is null or me is null then raise exception 'Authentication required' using errcode='42501'; end if;
  select * into event_row from public.tbl_events
  where id=p_event_id and status='published' and not coalesce(is_deleted,false)
    and not coalesce(is_cancelled,false) for update;
  if event_row.id is null then raise exception 'Activity is unavailable'; end if;
  if not private.has_active_partner(event_row.created_by) then
    raise exception 'Paid checkout is unavailable while the Partner account is not approved' using errcode='42501';
  end if;
  if event_row.payment_collection_mode<>'cashfree' then raise exception 'Online checkout is unavailable'; end if;
  perform private.assert_registration_complete(p_event_id,me);
  if event_row.created_by=me then raise exception 'Hosts cannot pay to join their own activity'; end if;
  if event_row.registration_close_time is not null and event_row.registration_close_time<now() then raise exception 'Registration is closed'; end if;
  if not event_row.is_paid or event_row.price<=0 then raise exception 'This activity does not require payment'; end if;
  if coalesce(event_row.currency,'INR')<>'INR' then raise exception 'Only INR activities are supported'; end if;
  amount_minor:=round(event_row.price*100)::bigint;
  if amount_minor<=0 or abs(event_row.price*100-amount_minor)>0.000001 then raise exception 'Activity price must have at most two decimal places'; end if;
  select * into participation from public.tbl_event_participants
  where event_id=p_event_id and user_id=me for update;
  if participation.status in ('approved','going') then raise exception 'You have already joined this activity'; end if;
  if event_row.join_type='approval' and coalesce(participation.status,'')<>'payment_required' then raise exception 'Host approval is required before payment'; end if;
  update public.tbl_activity_payments set status='expired',provider_status=coalesce(provider_status,'LOCAL_EXPIRED'),updated_at=now()
  where event_id=p_event_id and user_id=me and status in ('created','pending') and checkout_expires_at<=now();
  select * into payment from public.tbl_activity_payments
  where event_id=p_event_id and user_id=me and status in ('created','pending') and checkout_expires_at>now()
  order by created_at desc limit 1 for update;
  if payment.id is not null then
    if payment.amount_paisa<>amount_minor or payment.currency<>'INR' then raise exception 'The activity price changed; start a new payment attempt'; end if;
    return payment;
  end if;
  select count(*) into occupied from public.tbl_event_participants
  where event_id=p_event_id and user_id<>me and status in ('approved','going','payment_required');
  if event_row.max_participants is not null and occupied>=event_row.max_participants then raise exception 'Activity is full'; end if;
  if event_row.join_type<>'approval' then
    insert into public.tbl_event_participants(event_id,user_id,status,responded_at,joined_at)
    values(p_event_id,me,'payment_required',null,null)
    on conflict(event_id,user_id) do update set status=case when public.tbl_event_participants.status in ('approved','going')
      then public.tbl_event_participants.status else 'payment_required' end,responded_at=null,joined_at=null;
  end if;
  generated_order_id:='wn_'||p_event_id::text||'_'||me::text||'_'||substr(replace(gen_random_uuid()::text,'-',''),1,20);
  insert into public.tbl_activity_payments(event_id,user_id,partner_user_id,provider_order_id,amount_paisa,currency,status,checkout_expires_at)
  values(p_event_id,me,event_row.created_by,generated_order_id,amount_minor,'INR','created',now()+interval '20 minutes')
  returning * into payment;
  return payment;
end $$;

create or replace function public.finalize_activity_payment(
  p_order_id text,p_provider_payment_id text,p_amount_paisa bigint,p_currency text,
  p_provider_status text,p_provider_metadata jsonb default '{}'::jsonb
) returns public.tbl_activity_payments language plpgsql security definer set search_path='' as $$
declare payment public.tbl_activity_payments; event_row public.tbl_events; occupied integer; exception_reason text;
begin
  select * into payment from public.tbl_activity_payments where provider_order_id=p_order_id for update;
  if payment.id is null then raise exception 'Payment order not found'; end if;
  if payment.status='paid' then
    if payment.amount_paisa<>p_amount_paisa or payment.currency<>p_currency
      or coalesce(payment.provider_payment_id,'')<>coalesce(nullif(p_provider_payment_id,''),payment.provider_payment_id,'') then
      raise exception 'Conflicting paid-payment replay';
    end if;
    return payment;
  end if;
  if p_provider_status not in ('PAID','SUCCESS') then raise exception 'Provider has not confirmed payment'; end if;
  if payment.amount_paisa<>p_amount_paisa or payment.currency<>p_currency then raise exception 'Provider payment amount does not match the server ledger'; end if;
  select * into event_row from public.tbl_events where id=payment.event_id for update;
  if event_row.id is null or coalesce(event_row.is_deleted,false) or coalesce(event_row.is_cancelled,false) then
    exception_reason:='ACTIVITY_UNAVAILABLE_AFTER_PAYMENT';
  else
    select count(*) into occupied from public.tbl_event_participants
    where event_id=payment.event_id and user_id<>payment.user_id and status in ('approved','going');
    if event_row.max_participants is not null and occupied>=event_row.max_participants then
      exception_reason:='CAPACITY_UNAVAILABLE_AFTER_PAYMENT';
    end if;
  end if;
  update public.tbl_activity_payments set
    status='paid',provider_status=p_provider_status,
    provider_payment_id=coalesce(nullif(p_provider_payment_id,''),provider_payment_id),
    provider_metadata=coalesce(provider_metadata,'{}'::jsonb)||coalesce(p_provider_metadata,'{}'::jsonb),
    paid_at=coalesce(paid_at,now()),last_verified_at=now(),updated_at=now(),
    financial_status=case when exception_reason is null then 'PAYABLE' else 'REFUND_REQUIRED' end
  where id=payment.id returning * into payment;
  if exception_reason is null then
    insert into public.tbl_event_participants(event_id,user_id,status,responded_at,joined_at)
    values(payment.event_id,payment.user_id,'approved',now(),now())
    on conflict(event_id,user_id) do update set status='approved',responded_at=now(),joined_at=coalesce(public.tbl_event_participants.joined_at,now());
    insert into public.tbl_partner_financial_events(payment_id,event_id,partner_user_id,participant_user_id,kind,status,amount_paisa,idempotency_key,provider_reference)
    values(payment.id,payment.event_id,event_row.created_by,payment.user_id,'PAYMENT','SUCCEEDED',payment.amount_paisa,'payment:'||payment.id::text,payment.provider_payment_id)
    on conflict(idempotency_key) do nothing;
    perform private.enqueue_notification(payment.user_id,'payment_confirmed','Payment confirmed',
      'Your payment is verified and your place is confirmed.',payment.event_id::text,null,jsonb_build_object('payment_id',payment.id));
    perform private.refresh_partner_settlement(payment.event_id);
  else
    update public.tbl_event_participants set status='left',responded_at=now(),joined_at=null
    where event_id=payment.event_id and user_id=payment.user_id;
    perform private.queue_required_refund(payment,exception_reason);
  end if;
  return payment;
end $$;

create or replace function public.cancel_activity(p_event_id integer)
returns void language plpgsql security definer set search_path='' as $$
declare me integer:=public.get_current_app_user_id(); payment public.tbl_activity_payments;
begin
  if not private.can_manage_activity(p_event_id,me) then raise exception 'Activity not found or not manageable' using errcode='42501'; end if;
  update public.tbl_events set is_cancelled=true,status='cancelled',updated_by=me,updated_at=now() where id=p_event_id;
  for payment in select * from public.tbl_activity_payments where event_id=p_event_id and status='paid' and financial_status not in ('REFUNDED','REVERSED') loop
    perform private.queue_required_refund(payment,'ACTIVITY_CANCELLED_BY_HOST');
  end loop;
  update public.tbl_partner_settlements set status='ON_HOLD',note='Activity cancelled; refund review required',updated_at=now()
  where event_id=p_event_id and status<>'PAID';
end $$;

create or replace function private.get_partner_dashboard()
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare me integer:=public.get_current_app_user_id(); activities jsonb; summary jsonb;
begin
  if auth.uid() is null or not private.has_active_partner(me) then raise exception 'Approved Partner account required' using errcode='42501'; end if;
  with rows as (
    select e.id,e.title,e.event_start_time,e.event_end_time,e.price,e.status,e.visibility_type,e.max_participants capacity,
      (select count(*) from public.tbl_event_participants p where p.event_id=e.id and p.status<>'left') registration_count,
      (select count(*) from public.tbl_event_participants p where p.event_id=e.id and p.status='pending') pending_count,
      (select count(*) from public.tbl_event_participants p where p.event_id=e.id and p.status='approved') approved_count,
      (select count(*) from public.tbl_event_participants p where p.event_id=e.id and p.status='rejected') rejected_count,
      coalesce(s.gross_paisa,0) gross_paisa,coalesce(s.platform_fee_paisa,0) platform_fee_paisa,
      coalesce(s.gst_paisa,0) gst_paisa,coalesce(s.refund_paisa,0) refund_paisa,
      coalesce(s.expected_net_paisa,0) expected_net_paisa,s.status settlement_status,
      s.eligible_at,s.due_at,s.paid_at settlement_paid_at,s.payout_reference
    from public.tbl_events e left join public.tbl_partner_settlements s on s.event_id=e.id
    where e.created_by=me
  )
  select coalesce(jsonb_agg(to_jsonb(rows) order by event_start_time desc),'[]'::jsonb),
    jsonb_build_object('hosted_activities',count(*),'total_registrations',coalesce(sum(registration_count),0),
      'pending_registrations',coalesce(sum(pending_count),0),'approved_registrations',coalesce(sum(approved_count),0),
      'rejected_registrations',coalesce(sum(rejected_count),0),'gross_paisa',coalesce(sum(gross_paisa),0),
      'platform_fee_paisa',coalesce(sum(platform_fee_paisa),0),'gst_paisa',coalesce(sum(gst_paisa),0),
      'refund_paisa',coalesce(sum(refund_paisa),0),'expected_net_paisa',coalesce(sum(expected_net_paisa),0),
      'platform_fee_bps',private.platform_fee_bps())
  into activities,summary from rows;
  return jsonb_build_object('summary',summary,'activities',activities);
end $$;

create or replace function private.get_partner_transactions(p_event_id integer default null)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare me integer:=public.get_current_app_user_id(); result jsonb;
begin
  if auth.uid() is null or not private.has_active_partner(me) then raise exception 'Approved Partner account required' using errcode='42501'; end if;
  if p_event_id is not null and not private.partner_owns_activity(p_event_id) then raise exception 'Activity ownership required' using errcode='42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'payment_id',p.id::text,'event_id',e.id,'activity_title',e.title,
    'display_name',u.fullname,'paid_at',p.paid_at,'amount_paisa',p.amount_paisa,
    'platform_fee_bps',p.platform_fee_bps,'platform_fee_paisa',p.platform_fee_paisa,
    'gst_bps',p.gst_bps,'gst_paisa',p.gst_paisa,'gst_basis',p.gst_basis,
    'partner_net_paisa',p.partner_net_paisa,'financial_status',p.financial_status,
    'settlement_status',s.status,'settlement_due_at',s.due_at,'payout_reference',s.payout_reference
  ) order by p.paid_at desc),'[]'::jsonb) into result
  from public.tbl_activity_payments p join public.tbl_events e on e.id=p.event_id
  join public.tbl_users u on u.id=p.user_id
  left join public.tbl_partner_settlements s on s.event_id=e.id
  where e.created_by=me and (p_event_id is null or e.id=p_event_id) and p.status='paid';
  return result;
end $$;

create or replace function private.admin_list_partner_finance(p_status text default null)
returns jsonb language plpgsql stable security definer set search_path='' as $$
declare result jsonb;
begin
  if not private.is_finance_admin() then raise exception 'Finance admin access required' using errcode='42501'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'settlement_id',s.id,'event_id',s.event_id,'activity_title',e.title,
    'partner_user_id',s.partner_user_id,'partner_name',u.fullname,'business_name',p.business_name,
    'status',s.status,'gross_paisa',s.gross_paisa,'platform_fee_paisa',s.platform_fee_paisa,
    'gst_paisa',s.gst_paisa,'refund_paisa',s.refund_paisa,'expected_net_paisa',s.expected_net_paisa,
    'eligible_at',s.eligible_at,'due_at',s.due_at,'paid_at',s.paid_at,
    'payout_reference',s.payout_reference,'note',s.note
  ) order by s.due_at nulls last),'[]'::jsonb) into result
  from public.tbl_partner_settlements s join public.tbl_events e on e.id=s.event_id
  join public.tbl_users u on u.id=s.partner_user_id
  left join public.tbl_partner_profiles p on p.user_id=s.partner_user_id
  where p_status is null or s.status=upper(p_status);
  return result;
end $$;

create or replace function public.admin_list_partner_finance(p_status text default null)
returns jsonb language sql stable security invoker set search_path='' as $$
  select private.admin_list_partner_finance(p_status)
$$;

create or replace function private.admin_update_partner_finance_config(
  p_platform_fee_bps integer,p_gst_enabled boolean,p_gst_bps integer,p_gst_basis text,
  p_settlement_days integer,p_reason text
) returns jsonb language plpgsql security definer set search_path='' as $$
declare me integer:=public.get_current_app_user_id(); result public.tbl_partner_finance_config;
begin
  if not private.is_finance_admin() or me is null then raise exception 'Finance admin access required' using errcode='42501'; end if;
  if p_platform_fee_bps not between 0 and 10000 or p_settlement_days not between 0 and 90 then
    raise exception 'Invalid fee or settlement window' using errcode='22023';
  end if;
  if (not p_gst_enabled and (p_gst_bps<>0 or p_gst_basis<>'disabled'))
     or (p_gst_enabled and (p_gst_bps not between 1 and 10000 or p_gst_basis not in ('gross','platform_fee'))) then
    raise exception 'GST rate and basis must be explicitly configured together' using errcode='22023';
  end if;
  if nullif(btrim(coalesce(p_reason,'')),'') is null then raise exception 'A configuration change reason is required'; end if;
  update public.tbl_partner_finance_config set
    platform_fee_bps=p_platform_fee_bps,gst_enabled=p_gst_enabled,gst_bps=p_gst_bps,
    gst_basis=p_gst_basis,settlement_days=p_settlement_days,updated_at=now(),updated_by=me
  where singleton returning * into result;
  insert into public.tbl_partner_finance_config_history(
    platform_fee_bps,gst_enabled,gst_bps,gst_basis,settlement_days,changed_by,reason
  ) values(p_platform_fee_bps,p_gst_enabled,p_gst_bps,p_gst_basis,p_settlement_days,me,btrim(p_reason));
  insert into public.tbl_partner_finance_audit(actor_user_id,action,entity_type,entity_id,after_data,reason)
  values(me,'FINANCE_CONFIG_CHANGED','finance_config','singleton',to_jsonb(result),btrim(p_reason));
  return to_jsonb(result);
end $$;

create or replace function public.admin_update_partner_finance_config(
  p_platform_fee_bps integer,p_gst_enabled boolean,p_gst_bps integer,p_gst_basis text,
  p_settlement_days integer,p_reason text
) returns jsonb language sql security invoker set search_path='' as $$
  select private.admin_update_partner_finance_config(
    p_platform_fee_bps,p_gst_enabled,p_gst_bps,p_gst_basis,p_settlement_days,p_reason
  )
$$;

create or replace function private.admin_update_partner_settlement(
  p_settlement_id bigint,p_status text,p_payout_reference text default null,p_note text default null
) returns jsonb language plpgsql security definer set search_path='' as $$
declare me integer:=public.get_current_app_user_id(); before_row public.tbl_partner_settlements; after_row public.tbl_partner_settlements; target text:=upper(p_status);
begin
  if not private.is_finance_admin() or me is null then raise exception 'Finance admin access required' using errcode='42501'; end if;
  if target not in ('PENDING','PROCESSING','PAID','FAILED','ON_HOLD') then raise exception 'Invalid settlement status'; end if;
  if target='PAID' and nullif(btrim(coalesce(p_payout_reference,'')),'') is null then raise exception 'A payout reference is required before marking paid'; end if;
  select * into before_row from public.tbl_partner_settlements where id=p_settlement_id for update;
  if before_row.id is null then raise exception 'Settlement not found'; end if;
  if target='PAID' and (before_row.eligible_at is null or before_row.eligible_at>now()) then raise exception 'Settlement is not eligible yet'; end if;
  update public.tbl_partner_settlements set status=target,
    payout_reference=coalesce(nullif(btrim(coalesce(p_payout_reference,'')),''),payout_reference),
    note=nullif(btrim(coalesce(p_note,'')),''),paid_at=case when target='PAID' then now() else paid_at end,
    updated_by=me,updated_at=now() where id=p_settlement_id returning * into after_row;
  if target='PAID' then update public.tbl_activity_payments set financial_status='SETTLED'
    where event_id=after_row.event_id and status='paid' and financial_status='PAYABLE'; end if;
  insert into public.tbl_partner_finance_audit(actor_user_id,action,entity_type,entity_id,before_data,after_data,reason)
  values(me,'SETTLEMENT_STATUS_CHANGED','settlement',p_settlement_id::text,to_jsonb(before_row),to_jsonb(after_row),p_note);
  perform private.enqueue_notification(after_row.partner_user_id,'partner_settlement_update','Settlement updated',
    'Settlement status: '||target,after_row.event_id::text,me,jsonb_build_object('settlement_id',after_row.id,'status',target));
  return to_jsonb(after_row);
end $$;

create or replace function public.admin_update_partner_settlement(
  p_settlement_id bigint,p_status text,p_payout_reference text default null,p_note text default null
) returns jsonb language sql security invoker set search_path='' as $$
  select private.admin_update_partner_settlement(p_settlement_id,p_status,p_payout_reference,p_note)
$$;

-- Tight grants. Private functions are never client entry points.
revoke all on function private.normalize_partner_status(),private.has_active_partner(integer),
  private.sync_partner_capability(),private.is_finance_admin(),private.mask_financial_value(text,integer),
  private.get_my_partner_profile(),private.submit_partner_application(jsonb),
  private.save_my_partner_profile(text,text,text),private.admin_list_partner_applications(text),
  private.admin_review_partner_application(integer,text,text),private.enforce_partner_paid_hosting(),
  private.platform_fee_bps(),private.snapshot_activity_payment_fee(),private.block_immutable_partner_records(),
  private.refresh_partner_settlement(integer),private.queue_required_refund(public.tbl_activity_payments,text),
  private.get_partner_dashboard(),private.get_partner_transactions(integer),
  private.admin_list_partner_finance(text),
  private.admin_update_partner_finance_config(integer,boolean,integer,text,integer,text),
  private.admin_update_partner_settlement(bigint,text,text,text)
from public,anon,authenticated;

revoke all on function public.submit_partner_application(jsonb),public.get_my_partner_profile(),
  public.save_my_partner_profile(text,text,text),public.admin_list_partner_applications(text),
  public.admin_review_partner_application(integer,text,text),public.admin_list_partner_finance(text),
  public.admin_update_partner_finance_config(integer,boolean,integer,text,integer,text),
  public.admin_update_partner_settlement(bigint,text,text,text)
from public,anon;

grant execute on function public.submit_partner_application(jsonb),public.get_my_partner_profile(),
  public.save_my_partner_profile(text,text,text),public.admin_list_partner_applications(text),
  public.admin_review_partner_application(integer,text,text),public.admin_list_partner_finance(text),
  public.admin_update_partner_finance_config(integer,boolean,integer,text,integer,text),
  public.admin_update_partner_settlement(bigint,text,text,text)
to authenticated;

revoke all on function public.finalize_activity_payment(text,text,bigint,text,text,jsonb)
from public,anon,authenticated;
grant execute on function public.finalize_activity_payment(text,text,bigint,text,text,jsonb) to service_role;

-- The Edge order creator calls this as the authenticated user; all values remain server-derived.
revoke all on function public.prepare_activity_payment(integer) from public,anon;
grant execute on function public.prepare_activity_payment(integer) to authenticated,service_role;
